/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace LibAsset {
  export type AssetTypeStruct = {
    assetClass: PromiseOrValue<BytesLike>;
    data: PromiseOrValue<BytesLike>;
  };

  export type AssetTypeStructOutput = [string, string] & {
    assetClass: string;
    data: string;
  };

  export type AssetStruct = {
    assetType: LibAsset.AssetTypeStruct;
    data: PromiseOrValue<BytesLike>;
  };

  export type AssetStructOutput = [LibAsset.AssetTypeStructOutput, string] & {
    assetType: LibAsset.AssetTypeStructOutput;
    data: string;
  };
}

export declare namespace LibSignature {
  export type OrderStruct = {
    maker: PromiseOrValue<string>;
    makeAssets: LibAsset.AssetStruct[];
    taker: PromiseOrValue<string>;
    takeAssets: LibAsset.AssetStruct[];
    salt: PromiseOrValue<BigNumberish>;
    start: PromiseOrValue<BigNumberish>;
    end: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    auctionType: PromiseOrValue<BigNumberish>;
  };

  export type OrderStructOutput = [
    string,
    LibAsset.AssetStructOutput[],
    string,
    LibAsset.AssetStructOutput[],
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number
  ] & {
    maker: string;
    makeAssets: LibAsset.AssetStructOutput[];
    taker: string;
    takeAssets: LibAsset.AssetStructOutput[];
    salt: BigNumber;
    start: BigNumber;
    end: BigNumber;
    nonce: BigNumber;
    auctionType: number;
  };
}

export interface MarketplaceInterface extends utils.Interface {
  functions: {
    "MAX_PROTOCOL_FEE()": FunctionFragment;
    "MAX_ROYALTY()": FunctionFragment;
    "aggregator(address)": FunctionFragment;
    "approveOrder_((address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8))": FunctionFragment;
    "buyNow((address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8),address,uint8,bytes32,bytes32)": FunctionFragment;
    "cancel((address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8))": FunctionFragment;
    "cancelledOrFinalized(bytes32)": FunctionFragment;
    "editAggregator(address,bool)": FunctionFragment;
    "executeSwap((address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8),(address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8),uint8[2],bytes32[2],bytes32[2])": FunctionFragment;
    "funToken()": FunctionFragment;
    "funTokenDiscount()": FunctionFragment;
    "gkContract()": FunctionFragment;
    "gkFee()": FunctionFragment;
    "incrementNonce()": FunctionFragment;
    "initialize(address,address,address,address,address,address,address,address,address)": FunctionFragment;
    "marketplaceEvent()": FunctionFragment;
    "modifyWhitelist(address,bool)": FunctionFragment;
    "nftBuyContract()": FunctionFragment;
    "nftProfile()": FunctionFragment;
    "nonces(address)": FunctionFragment;
    "offerGk()": FunctionFragment;
    "offerProfile()": FunctionFragment;
    "orderApproved((address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8))": FunctionFragment;
    "owner()": FunctionFragment;
    "profileFee()": FunctionFragment;
    "protocolFee()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "proxies(bytes4)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "royaltyInfo(address)": FunctionFragment;
    "setFunToken(address)": FunctionFragment;
    "setFunTokenDiscount(uint48)": FunctionFragment;
    "setGkContract(address)": FunctionFragment;
    "setNftBuyContract(address)": FunctionFragment;
    "setNftProfile(address)": FunctionFragment;
    "setRoyalty(address,address,uint256)": FunctionFragment;
    "setRoyaltyOwnerAdmin(address,address,uint256)": FunctionFragment;
    "setTransferProxy(bytes4,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unusedVar()": FunctionFragment;
    "updateFee(uint256,uint256)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "validateOrder_((address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8),uint8,bytes32,bytes32)": FunctionFragment;
    "validationLogic()": FunctionFragment;
    "whitelistERC20(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_PROTOCOL_FEE"
      | "MAX_ROYALTY"
      | "aggregator"
      | "approveOrder_"
      | "buyNow"
      | "cancel"
      | "cancelledOrFinalized"
      | "editAggregator"
      | "executeSwap"
      | "funToken"
      | "funTokenDiscount"
      | "gkContract"
      | "gkFee"
      | "incrementNonce"
      | "initialize"
      | "marketplaceEvent"
      | "modifyWhitelist"
      | "nftBuyContract"
      | "nftProfile"
      | "nonces"
      | "offerGk"
      | "offerProfile"
      | "orderApproved"
      | "owner"
      | "profileFee"
      | "protocolFee"
      | "proxiableUUID"
      | "proxies"
      | "renounceOwnership"
      | "royaltyInfo"
      | "setFunToken"
      | "setFunTokenDiscount"
      | "setGkContract"
      | "setNftBuyContract"
      | "setNftProfile"
      | "setRoyalty"
      | "setRoyaltyOwnerAdmin"
      | "setTransferProxy"
      | "transferOwnership"
      | "unusedVar"
      | "updateFee"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "validateOrder_"
      | "validationLogic"
      | "whitelistERC20"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_PROTOCOL_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ROYALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aggregator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "approveOrder_",
    values: [LibSignature.OrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "buyNow",
    values: [
      LibSignature.OrderStruct,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [LibSignature.OrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelledOrFinalized",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "editAggregator",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSwap",
    values: [
      LibSignature.OrderStruct,
      LibSignature.OrderStruct,
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
    ]
  ): string;
  encodeFunctionData(functionFragment: "funToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "funTokenDiscount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gkContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gkFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "incrementNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplaceEvent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "modifyWhitelist",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "nftBuyContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nonces",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "offerGk", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "offerProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orderApproved",
    values: [LibSignature.OrderStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profileFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxies",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFunToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFunTokenDiscount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setGkContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setNftBuyContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setNftProfile",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoyalty",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoyaltyOwnerAdmin",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferProxy",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unusedVar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateFee",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOrder_",
    values: [
      LibSignature.OrderStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validationLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistERC20",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_PROTOCOL_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ROYALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aggregator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveOrder_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyNow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelledOrFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "funToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "funTokenDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gkContract", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gkFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incrementNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplaceEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftBuyContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftProfile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "offerGk", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offerProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orderApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profileFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proxies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFunToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFunTokenDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGkContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNftBuyContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNftProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRoyalty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRoyaltyOwnerAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unusedVar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOrder_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validationLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistERC20",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "Approval(bytes32,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Cancel(bytes32,address)": EventFragment;
    "EditAggregator(address,bool)": EventFragment;
    "FunTokenDiscount(uint48)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "NonceIncremented(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ProtocolFeeChange(uint256,uint48,uint48,uint48,uint48)": EventFragment;
    "ProxyChange(bytes4,address)": EventFragment;
    "RoyaltyInfoChange(address,address,uint256,address)": EventFragment;
    "Transfer(tuple,address,address)": EventFragment;
    "Upgraded(address)": EventFragment;
    "WhitelistChange(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Cancel"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EditAggregator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FunTokenDiscount"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NonceIncremented"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProtocolFeeChange"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProxyChange"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoyaltyInfoChange"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WhitelistChange"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface ApprovalEventObject {
  structHash: string;
  maker: string;
}
export type ApprovalEvent = TypedEvent<[string, string], ApprovalEventObject>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface CancelEventObject {
  structHash: string;
  maker: string;
}
export type CancelEvent = TypedEvent<[string, string], CancelEventObject>;

export type CancelEventFilter = TypedEventFilter<CancelEvent>;

export interface EditAggregatorEventObject {
  aggregator: string;
  status: boolean;
}
export type EditAggregatorEvent = TypedEvent<
  [string, boolean],
  EditAggregatorEventObject
>;

export type EditAggregatorEventFilter = TypedEventFilter<EditAggregatorEvent>;

export interface FunTokenDiscountEventObject {
  discount: number;
}
export type FunTokenDiscountEvent = TypedEvent<
  [number],
  FunTokenDiscountEventObject
>;

export type FunTokenDiscountEventFilter =
  TypedEventFilter<FunTokenDiscountEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface NonceIncrementedEventObject {
  maker: string;
  newNonce: BigNumber;
}
export type NonceIncrementedEvent = TypedEvent<
  [string, BigNumber],
  NonceIncrementedEventObject
>;

export type NonceIncrementedEventFilter =
  TypedEventFilter<NonceIncrementedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ProtocolFeeChangeEventObject {
  publicFee: BigNumber;
  profileFee: number;
  gkFee: number;
  offerGk: number;
  offerProfile: number;
}
export type ProtocolFeeChangeEvent = TypedEvent<
  [BigNumber, number, number, number, number],
  ProtocolFeeChangeEventObject
>;

export type ProtocolFeeChangeEventFilter =
  TypedEventFilter<ProtocolFeeChangeEvent>;

export interface ProxyChangeEventObject {
  assetType: string;
  proxy: string;
}
export type ProxyChangeEvent = TypedEvent<
  [string, string],
  ProxyChangeEventObject
>;

export type ProxyChangeEventFilter = TypedEventFilter<ProxyChangeEvent>;

export interface RoyaltyInfoChangeEventObject {
  token: string;
  owner: string;
  percent: BigNumber;
  setter: string;
}
export type RoyaltyInfoChangeEvent = TypedEvent<
  [string, string, BigNumber, string],
  RoyaltyInfoChangeEventObject
>;

export type RoyaltyInfoChangeEventFilter =
  TypedEventFilter<RoyaltyInfoChangeEvent>;

export interface TransferEventObject {
  asset: LibAsset.AssetStructOutput;
  from: string;
  to: string;
}
export type TransferEvent = TypedEvent<
  [LibAsset.AssetStructOutput, string, string],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface WhitelistChangeEventObject {
  token: string;
  value: boolean;
}
export type WhitelistChangeEvent = TypedEvent<
  [string, boolean],
  WhitelistChangeEventObject
>;

export type WhitelistChangeEventFilter = TypedEventFilter<WhitelistChangeEvent>;

export interface Marketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_PROTOCOL_FEE(overrides?: CallOverrides): Promise<[number]>;

    MAX_ROYALTY(overrides?: CallOverrides): Promise<[number]>;

    aggregator(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    approveOrder_(
      order: LibSignature.OrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyNow(
      sellOrder: LibSignature.OrderStruct,
      recipient: PromiseOrValue<string>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancel(
      order: LibSignature.OrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelledOrFinalized(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    editAggregator(
      _aggregator: PromiseOrValue<string>,
      _status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeSwap(
      sellOrder: LibSignature.OrderStruct,
      buyOrder: LibSignature.OrderStruct,
      v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    funToken(overrides?: CallOverrides): Promise<[string]>;

    funTokenDiscount(overrides?: CallOverrides): Promise<[number]>;

    gkContract(overrides?: CallOverrides): Promise<[string]>;

    gkFee(overrides?: CallOverrides): Promise<[number]>;

    incrementNonce(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _transferProxy: PromiseOrValue<string>,
      _erc20TransferProxy: PromiseOrValue<string>,
      _cryptoKittyProxy: PromiseOrValue<string>,
      _stakingContract: PromiseOrValue<string>,
      _funToken: PromiseOrValue<string>,
      _validationLogic: PromiseOrValue<string>,
      _marketplaceEvent: PromiseOrValue<string>,
      _nftProfile: PromiseOrValue<string>,
      _gkContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    marketplaceEvent(overrides?: CallOverrides): Promise<[string]>;

    modifyWhitelist(
      _token: PromiseOrValue<string>,
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    nftBuyContract(overrides?: CallOverrides): Promise<[string]>;

    nftProfile(overrides?: CallOverrides): Promise<[string]>;

    nonces(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    offerGk(overrides?: CallOverrides): Promise<[number]>;

    offerProfile(overrides?: CallOverrides): Promise<[number]>;

    orderApproved(
      order: LibSignature.OrderStruct,
      overrides?: CallOverrides
    ): Promise<[boolean] & { approved: boolean }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    profileFee(overrides?: CallOverrides): Promise<[number]>;

    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    proxies(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    royaltyInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { owner: string; percent: BigNumber }>;

    setFunToken(
      _funToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFunTokenDiscount(
      _discount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setGkContract(
      _gkContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setNftBuyContract(
      _nftBuyContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setNftProfile(
      _nftProfile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRoyalty(
      nftContract: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRoyaltyOwnerAdmin(
      nftContract: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTransferProxy(
      assetType: PromiseOrValue<BytesLike>,
      proxy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unusedVar(overrides?: CallOverrides): Promise<[number]>;

    updateFee(
      feeType: PromiseOrValue<BigNumberish>,
      _newFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validateOrder_(
      order: LibSignature.OrderStruct,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    validationLogic(overrides?: CallOverrides): Promise<[string]>;

    whitelistERC20(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  MAX_PROTOCOL_FEE(overrides?: CallOverrides): Promise<number>;

  MAX_ROYALTY(overrides?: CallOverrides): Promise<number>;

  aggregator(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  approveOrder_(
    order: LibSignature.OrderStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyNow(
    sellOrder: LibSignature.OrderStruct,
    recipient: PromiseOrValue<string>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancel(
    order: LibSignature.OrderStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelledOrFinalized(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  editAggregator(
    _aggregator: PromiseOrValue<string>,
    _status: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeSwap(
    sellOrder: LibSignature.OrderStruct,
    buyOrder: LibSignature.OrderStruct,
    v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
    s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  funToken(overrides?: CallOverrides): Promise<string>;

  funTokenDiscount(overrides?: CallOverrides): Promise<number>;

  gkContract(overrides?: CallOverrides): Promise<string>;

  gkFee(overrides?: CallOverrides): Promise<number>;

  incrementNonce(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _transferProxy: PromiseOrValue<string>,
    _erc20TransferProxy: PromiseOrValue<string>,
    _cryptoKittyProxy: PromiseOrValue<string>,
    _stakingContract: PromiseOrValue<string>,
    _funToken: PromiseOrValue<string>,
    _validationLogic: PromiseOrValue<string>,
    _marketplaceEvent: PromiseOrValue<string>,
    _nftProfile: PromiseOrValue<string>,
    _gkContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  marketplaceEvent(overrides?: CallOverrides): Promise<string>;

  modifyWhitelist(
    _token: PromiseOrValue<string>,
    _val: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  nftBuyContract(overrides?: CallOverrides): Promise<string>;

  nftProfile(overrides?: CallOverrides): Promise<string>;

  nonces(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  offerGk(overrides?: CallOverrides): Promise<number>;

  offerProfile(overrides?: CallOverrides): Promise<number>;

  orderApproved(
    order: LibSignature.OrderStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  profileFee(overrides?: CallOverrides): Promise<number>;

  protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  proxies(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  royaltyInfo(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { owner: string; percent: BigNumber }>;

  setFunToken(
    _funToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFunTokenDiscount(
    _discount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setGkContract(
    _gkContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setNftBuyContract(
    _nftBuyContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setNftProfile(
    _nftProfile: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRoyalty(
    nftContract: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRoyaltyOwnerAdmin(
    nftContract: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTransferProxy(
    assetType: PromiseOrValue<BytesLike>,
    proxy: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unusedVar(overrides?: CallOverrides): Promise<number>;

  updateFee(
    feeType: PromiseOrValue<BigNumberish>,
    _newFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validateOrder_(
    order: LibSignature.OrderStruct,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[boolean, string]>;

  validationLogic(overrides?: CallOverrides): Promise<string>;

  whitelistERC20(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    MAX_PROTOCOL_FEE(overrides?: CallOverrides): Promise<number>;

    MAX_ROYALTY(overrides?: CallOverrides): Promise<number>;

    aggregator(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    approveOrder_(
      order: LibSignature.OrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    buyNow(
      sellOrder: LibSignature.OrderStruct,
      recipient: PromiseOrValue<string>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancel(
      order: LibSignature.OrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelledOrFinalized(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    editAggregator(
      _aggregator: PromiseOrValue<string>,
      _status: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeSwap(
      sellOrder: LibSignature.OrderStruct,
      buyOrder: LibSignature.OrderStruct,
      v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      overrides?: CallOverrides
    ): Promise<void>;

    funToken(overrides?: CallOverrides): Promise<string>;

    funTokenDiscount(overrides?: CallOverrides): Promise<number>;

    gkContract(overrides?: CallOverrides): Promise<string>;

    gkFee(overrides?: CallOverrides): Promise<number>;

    incrementNonce(overrides?: CallOverrides): Promise<void>;

    initialize(
      _transferProxy: PromiseOrValue<string>,
      _erc20TransferProxy: PromiseOrValue<string>,
      _cryptoKittyProxy: PromiseOrValue<string>,
      _stakingContract: PromiseOrValue<string>,
      _funToken: PromiseOrValue<string>,
      _validationLogic: PromiseOrValue<string>,
      _marketplaceEvent: PromiseOrValue<string>,
      _nftProfile: PromiseOrValue<string>,
      _gkContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    marketplaceEvent(overrides?: CallOverrides): Promise<string>;

    modifyWhitelist(
      _token: PromiseOrValue<string>,
      _val: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    nftBuyContract(overrides?: CallOverrides): Promise<string>;

    nftProfile(overrides?: CallOverrides): Promise<string>;

    nonces(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    offerGk(overrides?: CallOverrides): Promise<number>;

    offerProfile(overrides?: CallOverrides): Promise<number>;

    orderApproved(
      order: LibSignature.OrderStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    profileFee(overrides?: CallOverrides): Promise<number>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    proxies(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    royaltyInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { owner: string; percent: BigNumber }>;

    setFunToken(
      _funToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFunTokenDiscount(
      _discount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setGkContract(
      _gkContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setNftBuyContract(
      _nftBuyContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setNftProfile(
      _nftProfile: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRoyalty(
      nftContract: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRoyaltyOwnerAdmin(
      nftContract: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTransferProxy(
      assetType: PromiseOrValue<BytesLike>,
      proxy: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unusedVar(overrides?: CallOverrides): Promise<number>;

    updateFee(
      feeType: PromiseOrValue<BigNumberish>,
      _newFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    validateOrder_(
      order: LibSignature.OrderStruct,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    validationLogic(overrides?: CallOverrides): Promise<string>;

    whitelistERC20(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "Approval(bytes32,address)"(
      structHash?: null,
      maker?: PromiseOrValue<string> | null
    ): ApprovalEventFilter;
    Approval(
      structHash?: null,
      maker?: PromiseOrValue<string> | null
    ): ApprovalEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "Cancel(bytes32,address)"(
      structHash?: null,
      maker?: PromiseOrValue<string> | null
    ): CancelEventFilter;
    Cancel(
      structHash?: null,
      maker?: PromiseOrValue<string> | null
    ): CancelEventFilter;

    "EditAggregator(address,bool)"(
      aggregator?: PromiseOrValue<string> | null,
      status?: null
    ): EditAggregatorEventFilter;
    EditAggregator(
      aggregator?: PromiseOrValue<string> | null,
      status?: null
    ): EditAggregatorEventFilter;

    "FunTokenDiscount(uint48)"(discount?: null): FunTokenDiscountEventFilter;
    FunTokenDiscount(discount?: null): FunTokenDiscountEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "NonceIncremented(address,uint256)"(
      maker?: PromiseOrValue<string> | null,
      newNonce?: null
    ): NonceIncrementedEventFilter;
    NonceIncremented(
      maker?: PromiseOrValue<string> | null,
      newNonce?: null
    ): NonceIncrementedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "ProtocolFeeChange(uint256,uint48,uint48,uint48,uint48)"(
      publicFee?: null,
      profileFee?: null,
      gkFee?: null,
      offerGk?: null,
      offerProfile?: null
    ): ProtocolFeeChangeEventFilter;
    ProtocolFeeChange(
      publicFee?: null,
      profileFee?: null,
      gkFee?: null,
      offerGk?: null,
      offerProfile?: null
    ): ProtocolFeeChangeEventFilter;

    "ProxyChange(bytes4,address)"(
      assetType?: PromiseOrValue<BytesLike> | null,
      proxy?: null
    ): ProxyChangeEventFilter;
    ProxyChange(
      assetType?: PromiseOrValue<BytesLike> | null,
      proxy?: null
    ): ProxyChangeEventFilter;

    "RoyaltyInfoChange(address,address,uint256,address)"(
      token?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      percent?: null,
      setter?: PromiseOrValue<string> | null
    ): RoyaltyInfoChangeEventFilter;
    RoyaltyInfoChange(
      token?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      percent?: null,
      setter?: PromiseOrValue<string> | null
    ): RoyaltyInfoChangeEventFilter;

    "Transfer(tuple,address,address)"(
      asset?: null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): TransferEventFilter;
    Transfer(
      asset?: null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): TransferEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;

    "WhitelistChange(address,bool)"(
      token?: PromiseOrValue<string> | null,
      value?: null
    ): WhitelistChangeEventFilter;
    WhitelistChange(
      token?: PromiseOrValue<string> | null,
      value?: null
    ): WhitelistChangeEventFilter;
  };

  estimateGas: {
    MAX_PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_ROYALTY(overrides?: CallOverrides): Promise<BigNumber>;

    aggregator(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approveOrder_(
      order: LibSignature.OrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyNow(
      sellOrder: LibSignature.OrderStruct,
      recipient: PromiseOrValue<string>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancel(
      order: LibSignature.OrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelledOrFinalized(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    editAggregator(
      _aggregator: PromiseOrValue<string>,
      _status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeSwap(
      sellOrder: LibSignature.OrderStruct,
      buyOrder: LibSignature.OrderStruct,
      v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    funToken(overrides?: CallOverrides): Promise<BigNumber>;

    funTokenDiscount(overrides?: CallOverrides): Promise<BigNumber>;

    gkContract(overrides?: CallOverrides): Promise<BigNumber>;

    gkFee(overrides?: CallOverrides): Promise<BigNumber>;

    incrementNonce(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      _transferProxy: PromiseOrValue<string>,
      _erc20TransferProxy: PromiseOrValue<string>,
      _cryptoKittyProxy: PromiseOrValue<string>,
      _stakingContract: PromiseOrValue<string>,
      _funToken: PromiseOrValue<string>,
      _validationLogic: PromiseOrValue<string>,
      _marketplaceEvent: PromiseOrValue<string>,
      _nftProfile: PromiseOrValue<string>,
      _gkContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    marketplaceEvent(overrides?: CallOverrides): Promise<BigNumber>;

    modifyWhitelist(
      _token: PromiseOrValue<string>,
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    nftBuyContract(overrides?: CallOverrides): Promise<BigNumber>;

    nftProfile(overrides?: CallOverrides): Promise<BigNumber>;

    nonces(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    offerGk(overrides?: CallOverrides): Promise<BigNumber>;

    offerProfile(overrides?: CallOverrides): Promise<BigNumber>;

    orderApproved(
      order: LibSignature.OrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    profileFee(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    proxies(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    royaltyInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFunToken(
      _funToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFunTokenDiscount(
      _discount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setGkContract(
      _gkContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setNftBuyContract(
      _nftBuyContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setNftProfile(
      _nftProfile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRoyalty(
      nftContract: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRoyaltyOwnerAdmin(
      nftContract: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTransferProxy(
      assetType: PromiseOrValue<BytesLike>,
      proxy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unusedVar(overrides?: CallOverrides): Promise<BigNumber>;

    updateFee(
      feeType: PromiseOrValue<BigNumberish>,
      _newFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validateOrder_(
      order: LibSignature.OrderStruct,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validationLogic(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistERC20(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_PROTOCOL_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_ROYALTY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aggregator(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approveOrder_(
      order: LibSignature.OrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyNow(
      sellOrder: LibSignature.OrderStruct,
      recipient: PromiseOrValue<string>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancel(
      order: LibSignature.OrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelledOrFinalized(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    editAggregator(
      _aggregator: PromiseOrValue<string>,
      _status: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeSwap(
      sellOrder: LibSignature.OrderStruct,
      buyOrder: LibSignature.OrderStruct,
      v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    funToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    funTokenDiscount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gkContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gkFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    incrementNonce(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _transferProxy: PromiseOrValue<string>,
      _erc20TransferProxy: PromiseOrValue<string>,
      _cryptoKittyProxy: PromiseOrValue<string>,
      _stakingContract: PromiseOrValue<string>,
      _funToken: PromiseOrValue<string>,
      _validationLogic: PromiseOrValue<string>,
      _marketplaceEvent: PromiseOrValue<string>,
      _nftProfile: PromiseOrValue<string>,
      _gkContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    marketplaceEvent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    modifyWhitelist(
      _token: PromiseOrValue<string>,
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    nftBuyContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftProfile(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonces(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    offerGk(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    offerProfile(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    orderApproved(
      order: LibSignature.OrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    profileFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxies(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    royaltyInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFunToken(
      _funToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFunTokenDiscount(
      _discount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setGkContract(
      _gkContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setNftBuyContract(
      _nftBuyContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setNftProfile(
      _nftProfile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRoyalty(
      nftContract: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRoyaltyOwnerAdmin(
      nftContract: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTransferProxy(
      assetType: PromiseOrValue<BytesLike>,
      proxy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unusedVar(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateFee(
      feeType: PromiseOrValue<BigNumberish>,
      _newFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validateOrder_(
      order: LibSignature.OrderStruct,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validationLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    whitelistERC20(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
