/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type SigStruct = {
  v: PromiseOrValue<BigNumberish>;
  r: PromiseOrValue<BytesLike>;
  s: PromiseOrValue<BytesLike>;
};

export type SigStructOutput = [number, string, string] & {
  v: number;
  r: string;
  s: string;
};

export declare namespace LibAsset {
  export type AssetTypeStruct = {
    assetClass: PromiseOrValue<BytesLike>;
    data: PromiseOrValue<BytesLike>;
  };

  export type AssetTypeStructOutput = [string, string] & {
    assetClass: string;
    data: string;
  };

  export type AssetStruct = {
    assetType: LibAsset.AssetTypeStruct;
    data: PromiseOrValue<BytesLike>;
  };

  export type AssetStructOutput = [LibAsset.AssetTypeStructOutput, string] & {
    assetType: LibAsset.AssetTypeStructOutput;
    data: string;
  };
}

export declare namespace LibSignature {
  export type OrderStruct = {
    maker: PromiseOrValue<string>;
    makeAssets: LibAsset.AssetStruct[];
    taker: PromiseOrValue<string>;
    takeAssets: LibAsset.AssetStruct[];
    salt: PromiseOrValue<BigNumberish>;
    start: PromiseOrValue<BigNumberish>;
    end: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    auctionType: PromiseOrValue<BigNumberish>;
  };

  export type OrderStructOutput = [
    string,
    LibAsset.AssetStructOutput[],
    string,
    LibAsset.AssetStructOutput[],
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number
  ] & {
    maker: string;
    makeAssets: LibAsset.AssetStructOutput[];
    taker: string;
    takeAssets: LibAsset.AssetStructOutput[];
    salt: BigNumber;
    start: BigNumber;
    end: BigNumber;
    nonce: BigNumber;
    auctionType: number;
  };
}

export interface Marketplace_eventInterface extends utils.Interface {
  functions: {
    "emitBuyNow(bytes32,(address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8),uint8,bytes32,bytes32)": FunctionFragment;
    "emitExecuteSwap(bytes32,bytes32,(address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8),(address,((bytes4,bytes),bytes)[],address,((bytes4,bytes),bytes)[],uint256,uint256,uint256,uint256,uint8),uint8[2],bytes32[2],bytes32[2])": FunctionFragment;
    "initialize()": FunctionFragment;
    "marketPlace()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setMarketPlace(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "emitBuyNow"
      | "emitExecuteSwap"
      | "initialize"
      | "marketPlace"
      | "owner"
      | "renounceOwnership"
      | "setMarketPlace"
      | "transferOwnership"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "emitBuyNow",
    values: [
      PromiseOrValue<BytesLike>,
      LibSignature.OrderStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emitExecuteSwap",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      LibSignature.OrderStruct,
      LibSignature.OrderStruct,
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketPlace",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketPlace",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "emitBuyNow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emitExecuteSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketPlace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketPlace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "BuyNowInfo(bytes32,address)": EventFragment;
    "Match(bytes32,bytes32,uint8,tuple,tuple,bool)": EventFragment;
    "Match2A(bytes32,address,address,uint256,uint256,uint256,uint256)": EventFragment;
    "Match2B(bytes32,bytes[],bytes[],bytes4[],bytes[],bytes[],bytes4[])": EventFragment;
    "Match3A(bytes32,address,address,uint256,uint256,uint256,uint256)": EventFragment;
    "Match3B(bytes32,bytes[],bytes[],bytes4[],bytes[],bytes[],bytes4[])": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyNowInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Match"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Match2A"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Match2B"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Match3A"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Match3B"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface BuyNowInfoEventObject {
  makerStructHash: string;
  takerAddress: string;
}
export type BuyNowInfoEvent = TypedEvent<
  [string, string],
  BuyNowInfoEventObject
>;

export type BuyNowInfoEventFilter = TypedEventFilter<BuyNowInfoEvent>;

export interface MatchEventObject {
  makerStructHash: string;
  takerStructHash: string;
  auctionType: number;
  makerSig: SigStructOutput;
  takerSig: SigStructOutput;
  privateSale: boolean;
}
export type MatchEvent = TypedEvent<
  [string, string, number, SigStructOutput, SigStructOutput, boolean],
  MatchEventObject
>;

export type MatchEventFilter = TypedEventFilter<MatchEvent>;

export interface Match2AEventObject {
  makerStructHash: string;
  makerAddress: string;
  takerAddress: string;
  start: BigNumber;
  end: BigNumber;
  nonce: BigNumber;
  salt: BigNumber;
}
export type Match2AEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, BigNumber, BigNumber],
  Match2AEventObject
>;

export type Match2AEventFilter = TypedEventFilter<Match2AEvent>;

export interface Match2BEventObject {
  makerStructHash: string;
  sellerMakerOrderAssetData: string[];
  sellerMakerOrderAssetTypeData: string[];
  sellerMakerOrderAssetClass: string[];
  sellerTakerOrderAssetData: string[];
  sellerTakerOrderAssetTypeData: string[];
  sellerTakerOrderAssetClass: string[];
}
export type Match2BEvent = TypedEvent<
  [string, string[], string[], string[], string[], string[], string[]],
  Match2BEventObject
>;

export type Match2BEventFilter = TypedEventFilter<Match2BEvent>;

export interface Match3AEventObject {
  takerStructHash: string;
  makerAddress: string;
  takerAddress: string;
  start: BigNumber;
  end: BigNumber;
  nonce: BigNumber;
  salt: BigNumber;
}
export type Match3AEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, BigNumber, BigNumber],
  Match3AEventObject
>;

export type Match3AEventFilter = TypedEventFilter<Match3AEvent>;

export interface Match3BEventObject {
  takerStructHash: string;
  buyerMakerOrderAssetData: string[];
  buyerMakerOrderAssetTypeData: string[];
  buyerMakerOrderAssetClass: string[];
  buyerTakerOrderAssetData: string[];
  buyerTakerOrderAssetTypeData: string[];
  buyerTakerOrderAssetClass: string[];
}
export type Match3BEvent = TypedEvent<
  [string, string[], string[], string[], string[], string[], string[]],
  Match3BEventObject
>;

export type Match3BEventFilter = TypedEventFilter<Match3BEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface Marketplace_event extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Marketplace_eventInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    emitBuyNow(
      sellHash: PromiseOrValue<BytesLike>,
      sellOrder: LibSignature.OrderStruct,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emitExecuteSwap(
      sellHash: PromiseOrValue<BytesLike>,
      buyHash: PromiseOrValue<BytesLike>,
      sellOrder: LibSignature.OrderStruct,
      buyOrder: LibSignature.OrderStruct,
      v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    marketPlace(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMarketPlace(
      _marketPlace: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  emitBuyNow(
    sellHash: PromiseOrValue<BytesLike>,
    sellOrder: LibSignature.OrderStruct,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emitExecuteSwap(
    sellHash: PromiseOrValue<BytesLike>,
    buyHash: PromiseOrValue<BytesLike>,
    sellOrder: LibSignature.OrderStruct,
    buyOrder: LibSignature.OrderStruct,
    v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
    s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  marketPlace(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMarketPlace(
    _marketPlace: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    emitBuyNow(
      sellHash: PromiseOrValue<BytesLike>,
      sellOrder: LibSignature.OrderStruct,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    emitExecuteSwap(
      sellHash: PromiseOrValue<BytesLike>,
      buyHash: PromiseOrValue<BytesLike>,
      sellOrder: LibSignature.OrderStruct,
      buyOrder: LibSignature.OrderStruct,
      v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(overrides?: CallOverrides): Promise<void>;

    marketPlace(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setMarketPlace(
      _marketPlace: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "BuyNowInfo(bytes32,address)"(
      makerStructHash?: PromiseOrValue<BytesLike> | null,
      takerAddress?: null
    ): BuyNowInfoEventFilter;
    BuyNowInfo(
      makerStructHash?: PromiseOrValue<BytesLike> | null,
      takerAddress?: null
    ): BuyNowInfoEventFilter;

    "Match(bytes32,bytes32,uint8,tuple,tuple,bool)"(
      makerStructHash?: PromiseOrValue<BytesLike> | null,
      takerStructHash?: PromiseOrValue<BytesLike> | null,
      auctionType?: null,
      makerSig?: null,
      takerSig?: null,
      privateSale?: null
    ): MatchEventFilter;
    Match(
      makerStructHash?: PromiseOrValue<BytesLike> | null,
      takerStructHash?: PromiseOrValue<BytesLike> | null,
      auctionType?: null,
      makerSig?: null,
      takerSig?: null,
      privateSale?: null
    ): MatchEventFilter;

    "Match2A(bytes32,address,address,uint256,uint256,uint256,uint256)"(
      makerStructHash?: PromiseOrValue<BytesLike> | null,
      makerAddress?: null,
      takerAddress?: null,
      start?: null,
      end?: null,
      nonce?: null,
      salt?: null
    ): Match2AEventFilter;
    Match2A(
      makerStructHash?: PromiseOrValue<BytesLike> | null,
      makerAddress?: null,
      takerAddress?: null,
      start?: null,
      end?: null,
      nonce?: null,
      salt?: null
    ): Match2AEventFilter;

    "Match2B(bytes32,bytes[],bytes[],bytes4[],bytes[],bytes[],bytes4[])"(
      makerStructHash?: PromiseOrValue<BytesLike> | null,
      sellerMakerOrderAssetData?: null,
      sellerMakerOrderAssetTypeData?: null,
      sellerMakerOrderAssetClass?: null,
      sellerTakerOrderAssetData?: null,
      sellerTakerOrderAssetTypeData?: null,
      sellerTakerOrderAssetClass?: null
    ): Match2BEventFilter;
    Match2B(
      makerStructHash?: PromiseOrValue<BytesLike> | null,
      sellerMakerOrderAssetData?: null,
      sellerMakerOrderAssetTypeData?: null,
      sellerMakerOrderAssetClass?: null,
      sellerTakerOrderAssetData?: null,
      sellerTakerOrderAssetTypeData?: null,
      sellerTakerOrderAssetClass?: null
    ): Match2BEventFilter;

    "Match3A(bytes32,address,address,uint256,uint256,uint256,uint256)"(
      takerStructHash?: PromiseOrValue<BytesLike> | null,
      makerAddress?: null,
      takerAddress?: null,
      start?: null,
      end?: null,
      nonce?: null,
      salt?: null
    ): Match3AEventFilter;
    Match3A(
      takerStructHash?: PromiseOrValue<BytesLike> | null,
      makerAddress?: null,
      takerAddress?: null,
      start?: null,
      end?: null,
      nonce?: null,
      salt?: null
    ): Match3AEventFilter;

    "Match3B(bytes32,bytes[],bytes[],bytes4[],bytes[],bytes[],bytes4[])"(
      takerStructHash?: PromiseOrValue<BytesLike> | null,
      buyerMakerOrderAssetData?: null,
      buyerMakerOrderAssetTypeData?: null,
      buyerMakerOrderAssetClass?: null,
      buyerTakerOrderAssetData?: null,
      buyerTakerOrderAssetTypeData?: null,
      buyerTakerOrderAssetClass?: null
    ): Match3BEventFilter;
    Match3B(
      takerStructHash?: PromiseOrValue<BytesLike> | null,
      buyerMakerOrderAssetData?: null,
      buyerMakerOrderAssetTypeData?: null,
      buyerMakerOrderAssetClass?: null,
      buyerTakerOrderAssetData?: null,
      buyerTakerOrderAssetTypeData?: null,
      buyerTakerOrderAssetClass?: null
    ): Match3BEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    emitBuyNow(
      sellHash: PromiseOrValue<BytesLike>,
      sellOrder: LibSignature.OrderStruct,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emitExecuteSwap(
      sellHash: PromiseOrValue<BytesLike>,
      buyHash: PromiseOrValue<BytesLike>,
      sellOrder: LibSignature.OrderStruct,
      buyOrder: LibSignature.OrderStruct,
      v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    marketPlace(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMarketPlace(
      _marketPlace: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    emitBuyNow(
      sellHash: PromiseOrValue<BytesLike>,
      sellOrder: LibSignature.OrderStruct,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emitExecuteSwap(
      sellHash: PromiseOrValue<BytesLike>,
      buyHash: PromiseOrValue<BytesLike>,
      sellOrder: LibSignature.OrderStruct,
      buyOrder: LibSignature.OrderStruct,
      v: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      r: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      s: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    marketPlace(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMarketPlace(
      _marketPlace: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
