/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type BatchClaimProfileStruct = {
  profileUrl: PromiseOrValue<string>;
  tokenId: PromiseOrValue<BigNumberish>;
  recipient: PromiseOrValue<string>;
  hash: PromiseOrValue<BytesLike>;
  signature: PromiseOrValue<BytesLike>;
};

export type BatchClaimProfileStructOutput = [
  string,
  BigNumber,
  string,
  string,
  string
] & {
  profileUrl: string;
  tokenId: BigNumber;
  recipient: string;
  hash: string;
  signature: string;
};

export interface MaxProfilesInterface extends utils.Interface {
  functions: {
    "cancelledOrFinalized(bytes32)": FunctionFragment;
    "contract1()": FunctionFragment;
    "contract2()": FunctionFragment;
    "emptySlot()": FunctionFragment;
    "extendLicense(string,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "genKeyWhitelistOnly()": FunctionFragment;
    "genesisKeyBatchClaimProfile((string,uint256,address,bytes32,bytes)[])": FunctionFragment;
    "genesisKeyClaimNumber(uint256)": FunctionFragment;
    "genesisKeyContract()": FunctionFragment;
    "getFee(string,uint256)": FunctionFragment;
    "governor()": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
    "lengthPremium(uint256)": FunctionFragment;
    "maxProfilePerAddress()": FunctionFragment;
    "nftProfile()": FunctionFragment;
    "nftProfileHelperAddress()": FunctionFragment;
    "ownedProfileStake(string)": FunctionFragment;
    "owner()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "publicClaim(string,bytes32,bytes)": FunctionFragment;
    "publicClaimBool()": FunctionFragment;
    "publicMint(string,uint256,uint8,bytes32,bytes32,bytes32,bytes)": FunctionFragment;
    "publicMintBool()": FunctionFragment;
    "publicMinted(address)": FunctionFragment;
    "purchaseExpiredProfile(string,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "setContract1(address)": FunctionFragment;
    "setContract2(address)": FunctionFragment;
    "setGenKeyWhitelistOnly(bool)": FunctionFragment;
    "setGovernor(address)": FunctionFragment;
    "setLengthPremium(uint256,uint256)": FunctionFragment;
    "setMaxProfilePerAddress(uint88)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "setPublicClaim(bool)": FunctionFragment;
    "setPublicMint(bool)": FunctionFragment;
    "setSigner(address)": FunctionFragment;
    "setUsdc(address)": FunctionFragment;
    "setYearlyFee(uint96)": FunctionFragment;
    "signerAddress()": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "usdc_()": FunctionFragment;
    "verifySignature(bytes32,bytes)": FunctionFragment;
    "yearlyFee()": FunctionFragment;
    "yearsToOwn()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancelledOrFinalized"
      | "contract1"
      | "contract2"
      | "emptySlot"
      | "extendLicense"
      | "genKeyWhitelistOnly"
      | "genesisKeyBatchClaimProfile"
      | "genesisKeyClaimNumber"
      | "genesisKeyContract"
      | "getFee"
      | "governor"
      | "initialize"
      | "lengthPremium"
      | "maxProfilePerAddress"
      | "nftProfile"
      | "nftProfileHelperAddress"
      | "ownedProfileStake"
      | "owner"
      | "proxiableUUID"
      | "publicClaim"
      | "publicClaimBool"
      | "publicMint"
      | "publicMintBool"
      | "publicMinted"
      | "purchaseExpiredProfile"
      | "setContract1"
      | "setContract2"
      | "setGenKeyWhitelistOnly"
      | "setGovernor"
      | "setLengthPremium"
      | "setMaxProfilePerAddress"
      | "setOwner"
      | "setPublicClaim"
      | "setPublicMint"
      | "setSigner"
      | "setUsdc"
      | "setYearlyFee"
      | "signerAddress"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "usdc_"
      | "verifySignature"
      | "yearlyFee"
      | "yearsToOwn"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancelledOrFinalized",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "contract1", values?: undefined): string;
  encodeFunctionData(functionFragment: "contract2", values?: undefined): string;
  encodeFunctionData(functionFragment: "emptySlot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "extendLicense",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "genKeyWhitelistOnly",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "genesisKeyBatchClaimProfile",
    values: [BatchClaimProfileStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "genesisKeyClaimNumber",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "genesisKeyContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lengthPremium",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxProfilePerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftProfileHelperAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownedProfileStake",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicClaim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "publicClaimBool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMint",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "publicMintBool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMinted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseExpiredProfile",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setContract1",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setContract2",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setGenKeyWhitelistOnly",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLengthPremium",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxProfilePerAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPublicClaim",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPublicMint",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSigner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUsdc",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setYearlyFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "usdc_", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifySignature",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "yearlyFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "yearsToOwn",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelledOrFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contract1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contract2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "emptySlot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "extendLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genKeyWhitelistOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genesisKeyBatchClaimProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genesisKeyClaimNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genesisKeyContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lengthPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxProfilePerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftProfileHelperAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownedProfileStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicClaimBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publicMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicMintBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseExpiredProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContract1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContract2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGenKeyWhitelistOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLengthPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxProfilePerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPublicClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPublicMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSigner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUsdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setYearlyFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc_", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yearlyFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yearsToOwn", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "ExtendLicense(address,string,uint256,uint256,bool,address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "MintedProfile(address,string,uint256,uint256,uint256,address)": EventFragment;
    "NewLengthPremium(uint256,uint256)": EventFragment;
    "NewMaxProfile(uint88)": EventFragment;
    "NewYearlyFee(uint96)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExtendLicense"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintedProfile"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewLengthPremium"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewMaxProfile"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewYearlyFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface ExtendLicenseEventObject {
  _receiver: string;
  _profileUrl: string;
  _duration: BigNumber;
  _fee: BigNumber;
  _expired: boolean;
  _paymentToken: string;
}
export type ExtendLicenseEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, boolean, string],
  ExtendLicenseEventObject
>;

export type ExtendLicenseEventFilter = TypedEventFilter<ExtendLicenseEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface MintedProfileEventObject {
  _user: string;
  _val: string;
  tokenId: BigNumber;
  _duration: BigNumber;
  _fee: BigNumber;
  _paymentToken: string;
}
export type MintedProfileEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, string],
  MintedProfileEventObject
>;

export type MintedProfileEventFilter = TypedEventFilter<MintedProfileEvent>;

export interface NewLengthPremiumEventObject {
  _length: BigNumber;
  _premium: BigNumber;
}
export type NewLengthPremiumEvent = TypedEvent<
  [BigNumber, BigNumber],
  NewLengthPremiumEventObject
>;

export type NewLengthPremiumEventFilter =
  TypedEventFilter<NewLengthPremiumEvent>;

export interface NewMaxProfileEventObject {
  _max: BigNumber;
}
export type NewMaxProfileEvent = TypedEvent<
  [BigNumber],
  NewMaxProfileEventObject
>;

export type NewMaxProfileEventFilter = TypedEventFilter<NewMaxProfileEvent>;

export interface NewYearlyFeeEventObject {
  _fee: BigNumber;
}
export type NewYearlyFeeEvent = TypedEvent<
  [BigNumber],
  NewYearlyFeeEventObject
>;

export type NewYearlyFeeEventFilter = TypedEventFilter<NewYearlyFeeEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface MaxProfiles extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MaxProfilesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancelledOrFinalized(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    contract1(overrides?: CallOverrides): Promise<[string]>;

    contract2(overrides?: CallOverrides): Promise<[string]>;

    emptySlot(overrides?: CallOverrides): Promise<[string]>;

    extendLicense(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    genKeyWhitelistOnly(overrides?: CallOverrides): Promise<[boolean]>;

    genesisKeyBatchClaimProfile(
      claims: BatchClaimProfileStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    genesisKeyClaimNumber(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    genesisKeyContract(overrides?: CallOverrides): Promise<[string]>;

    getFee(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    governor(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _nftProfile: PromiseOrValue<string>,
      _governor: PromiseOrValue<string>,
      _nftProfileHelperAddress: PromiseOrValue<string>,
      _genesisKeyContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    lengthPremium(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxProfilePerAddress(overrides?: CallOverrides): Promise<[BigNumber]>;

    nftProfile(overrides?: CallOverrides): Promise<[string]>;

    nftProfileHelperAddress(overrides?: CallOverrides): Promise<[string]>;

    ownedProfileStake(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    publicClaim(
      profileUrl: PromiseOrValue<string>,
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    publicClaimBool(overrides?: CallOverrides): Promise<[boolean]>;

    publicMint(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    publicMintBool(overrides?: CallOverrides): Promise<[boolean]>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    purchaseExpiredProfile(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setContract1(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setContract2(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setGenKeyWhitelistOnly(
      _genKeyWhitelistOnly: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setGovernor(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLengthPremium(
      _length: PromiseOrValue<BigNumberish>,
      _premium: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMaxProfilePerAddress(
      _max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPublicClaim(
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPublicMint(
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSigner(
      _signer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUsdc(
      _usdc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setYearlyFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    signerAddress(overrides?: CallOverrides): Promise<[string]>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    usdc_(overrides?: CallOverrides): Promise<[string]>;

    verifySignature(
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    yearlyFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    yearsToOwn(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  cancelledOrFinalized(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  contract1(overrides?: CallOverrides): Promise<string>;

  contract2(overrides?: CallOverrides): Promise<string>;

  emptySlot(overrides?: CallOverrides): Promise<string>;

  extendLicense(
    profileUrl: PromiseOrValue<string>,
    duration: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  genKeyWhitelistOnly(overrides?: CallOverrides): Promise<boolean>;

  genesisKeyBatchClaimProfile(
    claims: BatchClaimProfileStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  genesisKeyClaimNumber(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  genesisKeyContract(overrides?: CallOverrides): Promise<string>;

  getFee(
    profileUrl: PromiseOrValue<string>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  governor(overrides?: CallOverrides): Promise<string>;

  initialize(
    _nftProfile: PromiseOrValue<string>,
    _governor: PromiseOrValue<string>,
    _nftProfileHelperAddress: PromiseOrValue<string>,
    _genesisKeyContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  lengthPremium(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxProfilePerAddress(overrides?: CallOverrides): Promise<BigNumber>;

  nftProfile(overrides?: CallOverrides): Promise<string>;

  nftProfileHelperAddress(overrides?: CallOverrides): Promise<string>;

  ownedProfileStake(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  publicClaim(
    profileUrl: PromiseOrValue<string>,
    hash: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  publicClaimBool(overrides?: CallOverrides): Promise<boolean>;

  publicMint(
    profileUrl: PromiseOrValue<string>,
    duration: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    hash: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  publicMintBool(overrides?: CallOverrides): Promise<boolean>;

  publicMinted(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  purchaseExpiredProfile(
    profileUrl: PromiseOrValue<string>,
    duration: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setContract1(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setContract2(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setGenKeyWhitelistOnly(
    _genKeyWhitelistOnly: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setGovernor(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLengthPremium(
    _length: PromiseOrValue<BigNumberish>,
    _premium: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMaxProfilePerAddress(
    _max: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPublicClaim(
    _val: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPublicMint(
    _val: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSigner(
    _signer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUsdc(
    _usdc: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setYearlyFee(
    _fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  signerAddress(overrides?: CallOverrides): Promise<string>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  usdc_(overrides?: CallOverrides): Promise<string>;

  verifySignature(
    hash: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  yearlyFee(overrides?: CallOverrides): Promise<BigNumber>;

  yearsToOwn(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    cancelledOrFinalized(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    contract1(overrides?: CallOverrides): Promise<string>;

    contract2(overrides?: CallOverrides): Promise<string>;

    emptySlot(overrides?: CallOverrides): Promise<string>;

    extendLicense(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    genKeyWhitelistOnly(overrides?: CallOverrides): Promise<boolean>;

    genesisKeyBatchClaimProfile(
      claims: BatchClaimProfileStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    genesisKeyClaimNumber(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    genesisKeyContract(overrides?: CallOverrides): Promise<string>;

    getFee(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<string>;

    initialize(
      _nftProfile: PromiseOrValue<string>,
      _governor: PromiseOrValue<string>,
      _nftProfileHelperAddress: PromiseOrValue<string>,
      _genesisKeyContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    lengthPremium(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxProfilePerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    nftProfile(overrides?: CallOverrides): Promise<string>;

    nftProfileHelperAddress(overrides?: CallOverrides): Promise<string>;

    ownedProfileStake(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    publicClaim(
      profileUrl: PromiseOrValue<string>,
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    publicClaimBool(overrides?: CallOverrides): Promise<boolean>;

    publicMint(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    publicMintBool(overrides?: CallOverrides): Promise<boolean>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    purchaseExpiredProfile(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setContract1(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setContract2(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setGenKeyWhitelistOnly(
      _genKeyWhitelistOnly: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setGovernor(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLengthPremium(
      _length: PromiseOrValue<BigNumberish>,
      _premium: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxProfilePerAddress(
      _max: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPublicClaim(
      _val: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPublicMint(
      _val: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSigner(
      _signer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUsdc(
      _usdc: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setYearlyFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    signerAddress(overrides?: CallOverrides): Promise<string>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    usdc_(overrides?: CallOverrides): Promise<string>;

    verifySignature(
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    yearlyFee(overrides?: CallOverrides): Promise<BigNumber>;

    yearsToOwn(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "ExtendLicense(address,string,uint256,uint256,bool,address)"(
      _receiver?: null,
      _profileUrl?: null,
      _duration?: null,
      _fee?: null,
      _expired?: null,
      _paymentToken?: null
    ): ExtendLicenseEventFilter;
    ExtendLicense(
      _receiver?: null,
      _profileUrl?: null,
      _duration?: null,
      _fee?: null,
      _expired?: null,
      _paymentToken?: null
    ): ExtendLicenseEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "MintedProfile(address,string,uint256,uint256,uint256,address)"(
      _user?: null,
      _val?: null,
      tokenId?: null,
      _duration?: null,
      _fee?: null,
      _paymentToken?: null
    ): MintedProfileEventFilter;
    MintedProfile(
      _user?: null,
      _val?: null,
      tokenId?: null,
      _duration?: null,
      _fee?: null,
      _paymentToken?: null
    ): MintedProfileEventFilter;

    "NewLengthPremium(uint256,uint256)"(
      _length?: null,
      _premium?: null
    ): NewLengthPremiumEventFilter;
    NewLengthPremium(
      _length?: null,
      _premium?: null
    ): NewLengthPremiumEventFilter;

    "NewMaxProfile(uint88)"(_max?: null): NewMaxProfileEventFilter;
    NewMaxProfile(_max?: null): NewMaxProfileEventFilter;

    "NewYearlyFee(uint96)"(_fee?: null): NewYearlyFeeEventFilter;
    NewYearlyFee(_fee?: null): NewYearlyFeeEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    cancelledOrFinalized(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contract1(overrides?: CallOverrides): Promise<BigNumber>;

    contract2(overrides?: CallOverrides): Promise<BigNumber>;

    emptySlot(overrides?: CallOverrides): Promise<BigNumber>;

    extendLicense(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    genKeyWhitelistOnly(overrides?: CallOverrides): Promise<BigNumber>;

    genesisKeyBatchClaimProfile(
      claims: BatchClaimProfileStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    genesisKeyClaimNumber(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    genesisKeyContract(overrides?: CallOverrides): Promise<BigNumber>;

    getFee(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _nftProfile: PromiseOrValue<string>,
      _governor: PromiseOrValue<string>,
      _nftProfileHelperAddress: PromiseOrValue<string>,
      _genesisKeyContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    lengthPremium(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxProfilePerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    nftProfile(overrides?: CallOverrides): Promise<BigNumber>;

    nftProfileHelperAddress(overrides?: CallOverrides): Promise<BigNumber>;

    ownedProfileStake(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    publicClaim(
      profileUrl: PromiseOrValue<string>,
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    publicClaimBool(overrides?: CallOverrides): Promise<BigNumber>;

    publicMint(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    publicMintBool(overrides?: CallOverrides): Promise<BigNumber>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    purchaseExpiredProfile(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setContract1(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setContract2(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setGenKeyWhitelistOnly(
      _genKeyWhitelistOnly: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setGovernor(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLengthPremium(
      _length: PromiseOrValue<BigNumberish>,
      _premium: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMaxProfilePerAddress(
      _max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPublicClaim(
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPublicMint(
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSigner(
      _signer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUsdc(
      _usdc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setYearlyFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    signerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    usdc_(overrides?: CallOverrides): Promise<BigNumber>;

    verifySignature(
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    yearlyFee(overrides?: CallOverrides): Promise<BigNumber>;

    yearsToOwn(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelledOrFinalized(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contract1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contract2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    emptySlot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    extendLicense(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    genKeyWhitelistOnly(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    genesisKeyBatchClaimProfile(
      claims: BatchClaimProfileStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    genesisKeyClaimNumber(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    genesisKeyContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFee(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _nftProfile: PromiseOrValue<string>,
      _governor: PromiseOrValue<string>,
      _nftProfileHelperAddress: PromiseOrValue<string>,
      _genesisKeyContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    lengthPremium(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxProfilePerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nftProfile(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftProfileHelperAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownedProfileStake(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicClaim(
      profileUrl: PromiseOrValue<string>,
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    publicClaimBool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicMint(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    publicMintBool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicMinted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    purchaseExpiredProfile(
      profileUrl: PromiseOrValue<string>,
      duration: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setContract1(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setContract2(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setGenKeyWhitelistOnly(
      _genKeyWhitelistOnly: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setGovernor(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLengthPremium(
      _length: PromiseOrValue<BigNumberish>,
      _premium: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMaxProfilePerAddress(
      _max: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPublicClaim(
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPublicMint(
      _val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSigner(
      _signer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUsdc(
      _usdc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setYearlyFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    signerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    usdc_(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verifySignature(
      hash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    yearlyFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    yearsToOwn(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
