/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type AddressTupleStruct = {
  cid: PromiseOrValue<BigNumberish>;
  chainAddr: PromiseOrValue<string>;
};

export type AddressTupleStructOutput = [number, string] & {
  cid: number;
  chainAddr: string;
};

export type RelatedProfilesStruct = {
  addr: PromiseOrValue<string>;
  profileUrl: PromiseOrValue<string>;
};

export type RelatedProfilesStructOutput = [string, string] & {
  addr: string;
  profileUrl: string;
};

export interface Nft_resolverInterface extends utils.Interface {
  functions: {
    "addAssociatedAddresses((uint8,string)[],string)": FunctionFragment;
    "associateSelfWithUsers(string[])": FunctionFragment;
    "associatedAddresses(string)": FunctionFragment;
    "associatedContract(string)": FunctionFragment;
    "clearAssociatedAddresses(string)": FunctionFragment;
    "clearAssociatedContract(string)": FunctionFragment;
    "evmBased(uint8)": FunctionFragment;
    "getAllAssociatedAddr(address,string)": FunctionFragment;
    "getApprovedEvm(address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "parseAddr(string)": FunctionFragment;
    "removeAssociatedAddress((uint8,string),string)": FunctionFragment;
    "removeAssociatedProfile(string)": FunctionFragment;
    "setAssociatedContract((uint8,string),string)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "setRegex(uint8,address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addAssociatedAddresses"
      | "associateSelfWithUsers"
      | "associatedAddresses"
      | "associatedContract"
      | "clearAssociatedAddresses"
      | "clearAssociatedContract"
      | "evmBased"
      | "getAllAssociatedAddr"
      | "getApprovedEvm"
      | "initialize"
      | "owner"
      | "parseAddr"
      | "removeAssociatedAddress"
      | "removeAssociatedProfile"
      | "setAssociatedContract"
      | "setOwner"
      | "setRegex"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAssociatedAddresses",
    values: [AddressTupleStruct[], PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "associateSelfWithUsers",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "associatedAddresses",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "associatedContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "clearAssociatedAddresses",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "clearAssociatedContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "evmBased",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAssociatedAddr",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovedEvm",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "parseAddr",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAssociatedAddress",
    values: [AddressTupleStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAssociatedProfile",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssociatedContract",
    values: [AddressTupleStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegex",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAssociatedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "associateSelfWithUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "associatedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "associatedContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearAssociatedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearAssociatedContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "evmBased", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllAssociatedAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovedEvm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "parseAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAssociatedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAssociatedProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssociatedContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRegex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "AssociateEvmUser(address,string,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "CancelledEvmAssociation(address,string,address)": EventFragment;
    "ClearAllAssociatedAddresses(address,string)": EventFragment;
    "UpdatedRegex(uint8,address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssociateEvmUser"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelledEvmAssociation"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ClearAllAssociatedAddresses"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedRegex"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface AssociateEvmUserEventObject {
  owner: string;
  profileUrl: string;
  associatedAddress: string;
}
export type AssociateEvmUserEvent = TypedEvent<
  [string, string, string],
  AssociateEvmUserEventObject
>;

export type AssociateEvmUserEventFilter =
  TypedEventFilter<AssociateEvmUserEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface CancelledEvmAssociationEventObject {
  owner: string;
  profileUrl: string;
  associatedAddresses: string;
}
export type CancelledEvmAssociationEvent = TypedEvent<
  [string, string, string],
  CancelledEvmAssociationEventObject
>;

export type CancelledEvmAssociationEventFilter =
  TypedEventFilter<CancelledEvmAssociationEvent>;

export interface ClearAllAssociatedAddressesEventObject {
  owner: string;
  profileUrl: string;
}
export type ClearAllAssociatedAddressesEvent = TypedEvent<
  [string, string],
  ClearAllAssociatedAddressesEventObject
>;

export type ClearAllAssociatedAddressesEventFilter =
  TypedEventFilter<ClearAllAssociatedAddressesEvent>;

export interface UpdatedRegexEventObject {
  _cid: number;
  _regexAddress: string;
}
export type UpdatedRegexEvent = TypedEvent<
  [number, string],
  UpdatedRegexEventObject
>;

export type UpdatedRegexEventFilter = TypedEventFilter<UpdatedRegexEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface Nft_resolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Nft_resolverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addAssociatedAddresses(
      inputTuples: AddressTupleStruct[],
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    associateSelfWithUsers(
      urls: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    associatedAddresses(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[AddressTupleStructOutput[]]>;

    associatedContract(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[AddressTupleStructOutput]>;

    clearAssociatedAddresses(
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    clearAssociatedContract(
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    evmBased(
      cid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getAllAssociatedAddr(
      _user: PromiseOrValue<string>,
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[AddressTupleStructOutput[]]>;

    getApprovedEvm(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[RelatedProfilesStructOutput[]]>;

    initialize(
      _nftProfile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    parseAddr(
      _a: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    removeAssociatedAddress(
      inputTuple: AddressTupleStruct,
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeAssociatedProfile(
      url: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAssociatedContract(
      inputTuple: AddressTupleStruct,
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRegex(
      _cid: PromiseOrValue<BigNumberish>,
      _regexContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addAssociatedAddresses(
    inputTuples: AddressTupleStruct[],
    profileUrl: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  associateSelfWithUsers(
    urls: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  associatedAddresses(
    profileUrl: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<AddressTupleStructOutput[]>;

  associatedContract(
    profileUrl: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<AddressTupleStructOutput>;

  clearAssociatedAddresses(
    profileUrl: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  clearAssociatedContract(
    profileUrl: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  evmBased(
    cid: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getAllAssociatedAddr(
    _user: PromiseOrValue<string>,
    profileUrl: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<AddressTupleStructOutput[]>;

  getApprovedEvm(
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<RelatedProfilesStructOutput[]>;

  initialize(
    _nftProfile: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  parseAddr(
    _a: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  removeAssociatedAddress(
    inputTuple: AddressTupleStruct,
    profileUrl: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeAssociatedProfile(
    url: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAssociatedContract(
    inputTuple: AddressTupleStruct,
    profileUrl: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRegex(
    _cid: PromiseOrValue<BigNumberish>,
    _regexContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addAssociatedAddresses(
      inputTuples: AddressTupleStruct[],
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    associateSelfWithUsers(
      urls: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    associatedAddresses(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<AddressTupleStructOutput[]>;

    associatedContract(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<AddressTupleStructOutput>;

    clearAssociatedAddresses(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    clearAssociatedContract(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    evmBased(
      cid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getAllAssociatedAddr(
      _user: PromiseOrValue<string>,
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<AddressTupleStructOutput[]>;

    getApprovedEvm(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<RelatedProfilesStructOutput[]>;

    initialize(
      _nftProfile: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    parseAddr(
      _a: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    removeAssociatedAddress(
      inputTuple: AddressTupleStruct,
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeAssociatedProfile(
      url: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setAssociatedContract(
      inputTuple: AddressTupleStruct,
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRegex(
      _cid: PromiseOrValue<BigNumberish>,
      _regexContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "AssociateEvmUser(address,string,address)"(
      owner?: PromiseOrValue<string> | null,
      profileUrl?: null,
      associatedAddress?: PromiseOrValue<string> | null
    ): AssociateEvmUserEventFilter;
    AssociateEvmUser(
      owner?: PromiseOrValue<string> | null,
      profileUrl?: null,
      associatedAddress?: PromiseOrValue<string> | null
    ): AssociateEvmUserEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "CancelledEvmAssociation(address,string,address)"(
      owner?: PromiseOrValue<string> | null,
      profileUrl?: null,
      associatedAddresses?: PromiseOrValue<string> | null
    ): CancelledEvmAssociationEventFilter;
    CancelledEvmAssociation(
      owner?: PromiseOrValue<string> | null,
      profileUrl?: null,
      associatedAddresses?: PromiseOrValue<string> | null
    ): CancelledEvmAssociationEventFilter;

    "ClearAllAssociatedAddresses(address,string)"(
      owner?: PromiseOrValue<string> | null,
      profileUrl?: null
    ): ClearAllAssociatedAddressesEventFilter;
    ClearAllAssociatedAddresses(
      owner?: PromiseOrValue<string> | null,
      profileUrl?: null
    ): ClearAllAssociatedAddressesEventFilter;

    "UpdatedRegex(uint8,address)"(
      _cid?: null,
      _regexAddress?: null
    ): UpdatedRegexEventFilter;
    UpdatedRegex(_cid?: null, _regexAddress?: null): UpdatedRegexEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    addAssociatedAddresses(
      inputTuples: AddressTupleStruct[],
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    associateSelfWithUsers(
      urls: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    associatedAddresses(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    associatedContract(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    clearAssociatedAddresses(
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    clearAssociatedContract(
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    evmBased(
      cid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllAssociatedAddr(
      _user: PromiseOrValue<string>,
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getApprovedEvm(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _nftProfile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    parseAddr(
      _a: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAssociatedAddress(
      inputTuple: AddressTupleStruct,
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeAssociatedProfile(
      url: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAssociatedContract(
      inputTuple: AddressTupleStruct,
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRegex(
      _cid: PromiseOrValue<BigNumberish>,
      _regexContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAssociatedAddresses(
      inputTuples: AddressTupleStruct[],
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    associateSelfWithUsers(
      urls: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    associatedAddresses(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    associatedContract(
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    clearAssociatedAddresses(
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    clearAssociatedContract(
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    evmBased(
      cid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllAssociatedAddr(
      _user: PromiseOrValue<string>,
      profileUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getApprovedEvm(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _nftProfile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    parseAddr(
      _a: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAssociatedAddress(
      inputTuple: AddressTupleStruct,
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeAssociatedProfile(
      url: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAssociatedContract(
      inputTuple: AddressTupleStruct,
      profileUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRegex(
      _cid: PromiseOrValue<BigNumberish>,
      _regexContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
