/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type ERC20DetailsStruct = {
  tokenAddrs: PromiseOrValue<string>[];
  amounts: PromiseOrValue<BigNumberish>[];
};

export type ERC20DetailsStructOutput = [string[], BigNumber[]] & {
  tokenAddrs: string[];
  amounts: BigNumber[];
};

export type TradeDetailsStruct = {
  marketId: PromiseOrValue<BigNumberish>;
  value: PromiseOrValue<BigNumberish>;
  tradeData: PromiseOrValue<BytesLike>;
};

export type TradeDetailsStructOutput = [BigNumber, BigNumber, string] & {
  marketId: BigNumber;
  value: BigNumber;
  tradeData: string;
};

export type FeeDetailsStruct = {
  _profileTokenId: PromiseOrValue<BigNumberish>;
  _wei: PromiseOrValue<BigNumberish>;
};

export type FeeDetailsStructOutput = [BigNumber, BigNumber] & {
  _profileTokenId: BigNumber;
  _wei: BigNumber;
};

export type MultiAssetInfoStruct = {
  conversionDetails: PromiseOrValue<BytesLike>[];
  dustTokens: PromiseOrValue<string>[];
  feeDetails: FeeDetailsStruct;
};

export type MultiAssetInfoStructOutput = [
  string[],
  string[],
  FeeDetailsStructOutput
] & {
  conversionDetails: string[];
  dustTokens: string[];
  feeDetails: FeeDetailsStructOutput;
};

export type ERC1155DetailsStruct = {
  tokenAddr: PromiseOrValue<string>;
  ids: PromiseOrValue<BigNumberish>[];
  amounts: PromiseOrValue<BigNumberish>[];
};

export type ERC1155DetailsStructOutput = [string, BigNumber[], BigNumber[]] & {
  tokenAddr: string;
  ids: BigNumber[];
  amounts: BigNumber[];
};

export type ApprovalsStruct = {
  token: PromiseOrValue<string>;
  operator: PromiseOrValue<string>;
  amount: PromiseOrValue<BigNumberish>;
};

export type ApprovalsStructOutput = [string, string, BigNumber] & {
  token: string;
  operator: string;
  amount: BigNumber;
};

export declare namespace SpecialTransferHelper {
  export type ERC721DetailsStruct = {
    tokenAddr: PromiseOrValue<string>;
    to: PromiseOrValue<string>[];
    ids: PromiseOrValue<BigNumberish>[];
  };

  export type ERC721DetailsStructOutput = [string, string[], BigNumber[]] & {
    tokenAddr: string;
    to: string[];
    ids: BigNumber[];
  };
}

export interface Nft_aggregatorInterface extends utils.Interface {
  functions: {
    "CRYPTO_PUNK()": FunctionFragment;
    "MOONCAT()": FunctionFragment;
    "baseFee()": FunctionFragment;
    "batchTrade((address[],uint256[]),(uint256,uint256,bytes)[],(bytes[],address[],(uint256,uint256)))": FunctionFragment;
    "batchTradeWithETH((uint256,uint256,bytes)[],address[],(uint256,uint256))": FunctionFragment;
    "converter()": FunctionFragment;
    "dao()": FunctionFragment;
    "extraBool()": FunctionFragment;
    "initialize(address,address,address)": FunctionFragment;
    "marketplaceRegistry()": FunctionFragment;
    "multiAssetSwap((address[],uint256[]),(address,address[],uint256[])[],(address,uint256[],uint256[])[],(uint256,uint256,bytes)[],(bytes[],address[],(uint256,uint256)))": FunctionFragment;
    "nftProfile()": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "onERC721Received(address,uint256,bytes)": FunctionFragment;
    "openForTrades()": FunctionFragment;
    "owner()": FunctionFragment;
    "percentFeeToDao()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "rescueERC1155(address,uint256[],uint256[],address)": FunctionFragment;
    "rescueERC20(address,address)": FunctionFragment;
    "rescueERC721(address,uint256[],address)": FunctionFragment;
    "rescueETH(address)": FunctionFragment;
    "rescueMooncat((address,address[],uint256[]))": FunctionFragment;
    "rescuePunk((address,address[],uint256[]))": FunctionFragment;
    "setBaseFee(uint256)": FunctionFragment;
    "setConverter(address)": FunctionFragment;
    "setDao(address)": FunctionFragment;
    "setDaoFee(uint256)": FunctionFragment;
    "setNftProfile(address)": FunctionFragment;
    "setOneTimeApproval((address,address,uint256)[])": FunctionFragment;
    "setOpenForTrades(bool)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CRYPTO_PUNK"
      | "MOONCAT"
      | "baseFee"
      | "batchTrade"
      | "batchTradeWithETH"
      | "converter"
      | "dao"
      | "extraBool"
      | "initialize"
      | "marketplaceRegistry"
      | "multiAssetSwap"
      | "nftProfile"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "onERC721Received(address,address,uint256,bytes)"
      | "onERC721Received(address,uint256,bytes)"
      | "openForTrades"
      | "owner"
      | "percentFeeToDao"
      | "proxiableUUID"
      | "rescueERC1155"
      | "rescueERC20"
      | "rescueERC721"
      | "rescueETH"
      | "rescueMooncat"
      | "rescuePunk"
      | "setBaseFee"
      | "setConverter"
      | "setDao"
      | "setDaoFee"
      | "setNftProfile"
      | "setOneTimeApproval"
      | "setOpenForTrades"
      | "setOwner"
      | "supportsInterface"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CRYPTO_PUNK",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MOONCAT", values?: undefined): string;
  encodeFunctionData(functionFragment: "baseFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "batchTrade",
    values: [ERC20DetailsStruct, TradeDetailsStruct[], MultiAssetInfoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTradeWithETH",
    values: [TradeDetailsStruct[], PromiseOrValue<string>[], FeeDetailsStruct]
  ): string;
  encodeFunctionData(functionFragment: "converter", values?: undefined): string;
  encodeFunctionData(functionFragment: "dao", values?: undefined): string;
  encodeFunctionData(functionFragment: "extraBool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplaceRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multiAssetSwap",
    values: [
      ERC20DetailsStruct,
      SpecialTransferHelper.ERC721DetailsStruct[],
      ERC1155DetailsStruct[],
      TradeDetailsStruct[],
      MultiAssetInfoStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nftProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received(address,address,uint256,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received(address,uint256,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openForTrades",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "percentFeeToDao",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueERC1155",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueERC20",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueERC721",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueETH",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueMooncat",
    values: [SpecialTransferHelper.ERC721DetailsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "rescuePunk",
    values: [SpecialTransferHelper.ERC721DetailsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setConverter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDao",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDaoFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setNftProfile",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOneTimeApproval",
    values: [ApprovalsStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setOpenForTrades",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "CRYPTO_PUNK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MOONCAT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchTradeWithETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "converter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dao", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "extraBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplaceRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiAssetSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received(address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openForTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "percentFeeToDao",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rescueETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rescueMooncat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rescuePunk", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBaseFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setConverter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDao", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setDaoFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setNftProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOneTimeApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOpenForTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "NewConverter(address)": EventFragment;
    "NewDao(address)": EventFragment;
    "NewNftProfile(address)": EventFragment;
    "NewOwner(address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewConverter"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewDao"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewNftProfile"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface NewConverterEventObject {
  _new: string;
}
export type NewConverterEvent = TypedEvent<[string], NewConverterEventObject>;

export type NewConverterEventFilter = TypedEventFilter<NewConverterEvent>;

export interface NewDaoEventObject {
  _new: string;
}
export type NewDaoEvent = TypedEvent<[string], NewDaoEventObject>;

export type NewDaoEventFilter = TypedEventFilter<NewDaoEvent>;

export interface NewNftProfileEventObject {
  _new: string;
}
export type NewNftProfileEvent = TypedEvent<[string], NewNftProfileEventObject>;

export type NewNftProfileEventFilter = TypedEventFilter<NewNftProfileEvent>;

export interface NewOwnerEventObject {
  _new: string;
}
export type NewOwnerEvent = TypedEvent<[string], NewOwnerEventObject>;

export type NewOwnerEventFilter = TypedEventFilter<NewOwnerEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface Nft_aggregator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Nft_aggregatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CRYPTO_PUNK(overrides?: CallOverrides): Promise<[string]>;

    MOONCAT(overrides?: CallOverrides): Promise<[string]>;

    baseFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    batchTrade(
      erc20Details: ERC20DetailsStruct,
      tradeDetails: TradeDetailsStruct[],
      tradeInfo: MultiAssetInfoStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchTradeWithETH(
      tradeDetails: TradeDetailsStruct[],
      dustTokens: PromiseOrValue<string>[],
      feeDetails: FeeDetailsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    converter(overrides?: CallOverrides): Promise<[string]>;

    dao(overrides?: CallOverrides): Promise<[string]>;

    extraBool(overrides?: CallOverrides): Promise<[boolean]>;

    initialize(
      _marketRegistry: PromiseOrValue<string>,
      _cryptoPunk: PromiseOrValue<string>,
      _mooncat: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    marketplaceRegistry(overrides?: CallOverrides): Promise<[string]>;

    multiAssetSwap(
      erc20Details: ERC20DetailsStruct,
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct[],
      erc1155Details: ERC1155DetailsStruct[],
      tradeDetails: TradeDetailsStruct[],
      tradeInfo: MultiAssetInfoStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    nftProfile(overrides?: CallOverrides): Promise<[string]>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "onERC721Received(address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    openForTrades(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    percentFeeToDao(overrides?: CallOverrides): Promise<[BigNumber]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    rescueERC1155(
      asset: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rescueERC20(
      asset: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rescueERC721(
      asset: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rescueETH(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rescueMooncat(
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rescuePunk(
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBaseFee(
      _baseFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setConverter(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDao(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDaoFee(
      _percentFeeToDao: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setNftProfile(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOneTimeApproval(
      _approvals: ApprovalsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOpenForTrades(
      _openForTrades: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  CRYPTO_PUNK(overrides?: CallOverrides): Promise<string>;

  MOONCAT(overrides?: CallOverrides): Promise<string>;

  baseFee(overrides?: CallOverrides): Promise<BigNumber>;

  batchTrade(
    erc20Details: ERC20DetailsStruct,
    tradeDetails: TradeDetailsStruct[],
    tradeInfo: MultiAssetInfoStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchTradeWithETH(
    tradeDetails: TradeDetailsStruct[],
    dustTokens: PromiseOrValue<string>[],
    feeDetails: FeeDetailsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  converter(overrides?: CallOverrides): Promise<string>;

  dao(overrides?: CallOverrides): Promise<string>;

  extraBool(overrides?: CallOverrides): Promise<boolean>;

  initialize(
    _marketRegistry: PromiseOrValue<string>,
    _cryptoPunk: PromiseOrValue<string>,
    _mooncat: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  marketplaceRegistry(overrides?: CallOverrides): Promise<string>;

  multiAssetSwap(
    erc20Details: ERC20DetailsStruct,
    erc721Details: SpecialTransferHelper.ERC721DetailsStruct[],
    erc1155Details: ERC1155DetailsStruct[],
    tradeDetails: TradeDetailsStruct[],
    tradeInfo: MultiAssetInfoStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  nftProfile(overrides?: CallOverrides): Promise<string>;

  onERC1155BatchReceived(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>[],
    arg3: PromiseOrValue<BigNumberish>[],
    arg4: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BigNumberish>,
    arg4: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "onERC721Received(address,address,uint256,bytes)"(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "onERC721Received(address,uint256,bytes)"(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  openForTrades(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  percentFeeToDao(overrides?: CallOverrides): Promise<BigNumber>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  rescueERC1155(
    asset: PromiseOrValue<string>,
    ids: PromiseOrValue<BigNumberish>[],
    amounts: PromiseOrValue<BigNumberish>[],
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rescueERC20(
    asset: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rescueERC721(
    asset: PromiseOrValue<string>,
    ids: PromiseOrValue<BigNumberish>[],
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rescueETH(
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rescueMooncat(
    erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rescuePunk(
    erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBaseFee(
    _baseFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setConverter(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDao(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDaoFee(
    _percentFeeToDao: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setNftProfile(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOneTimeApproval(
    _approvals: ApprovalsStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOpenForTrades(
    _openForTrades: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    _new: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CRYPTO_PUNK(overrides?: CallOverrides): Promise<string>;

    MOONCAT(overrides?: CallOverrides): Promise<string>;

    baseFee(overrides?: CallOverrides): Promise<BigNumber>;

    batchTrade(
      erc20Details: ERC20DetailsStruct,
      tradeDetails: TradeDetailsStruct[],
      tradeInfo: MultiAssetInfoStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    batchTradeWithETH(
      tradeDetails: TradeDetailsStruct[],
      dustTokens: PromiseOrValue<string>[],
      feeDetails: FeeDetailsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    converter(overrides?: CallOverrides): Promise<string>;

    dao(overrides?: CallOverrides): Promise<string>;

    extraBool(overrides?: CallOverrides): Promise<boolean>;

    initialize(
      _marketRegistry: PromiseOrValue<string>,
      _cryptoPunk: PromiseOrValue<string>,
      _mooncat: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    marketplaceRegistry(overrides?: CallOverrides): Promise<string>;

    multiAssetSwap(
      erc20Details: ERC20DetailsStruct,
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct[],
      erc1155Details: ERC1155DetailsStruct[],
      tradeDetails: TradeDetailsStruct[],
      tradeInfo: MultiAssetInfoStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    nftProfile(overrides?: CallOverrides): Promise<string>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    openForTrades(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    percentFeeToDao(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    rescueERC1155(
      asset: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    rescueERC20(
      asset: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    rescueERC721(
      asset: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    rescueETH(
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    rescueMooncat(
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    rescuePunk(
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setBaseFee(
      _baseFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setConverter(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDao(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDaoFee(
      _percentFeeToDao: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setNftProfile(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOneTimeApproval(
      _approvals: ApprovalsStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setOpenForTrades(
      _openForTrades: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "NewConverter(address)"(
      _new?: PromiseOrValue<string> | null
    ): NewConverterEventFilter;
    NewConverter(_new?: PromiseOrValue<string> | null): NewConverterEventFilter;

    "NewDao(address)"(_new?: PromiseOrValue<string> | null): NewDaoEventFilter;
    NewDao(_new?: PromiseOrValue<string> | null): NewDaoEventFilter;

    "NewNftProfile(address)"(
      _new?: PromiseOrValue<string> | null
    ): NewNftProfileEventFilter;
    NewNftProfile(
      _new?: PromiseOrValue<string> | null
    ): NewNftProfileEventFilter;

    "NewOwner(address)"(
      _new?: PromiseOrValue<string> | null
    ): NewOwnerEventFilter;
    NewOwner(_new?: PromiseOrValue<string> | null): NewOwnerEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    CRYPTO_PUNK(overrides?: CallOverrides): Promise<BigNumber>;

    MOONCAT(overrides?: CallOverrides): Promise<BigNumber>;

    baseFee(overrides?: CallOverrides): Promise<BigNumber>;

    batchTrade(
      erc20Details: ERC20DetailsStruct,
      tradeDetails: TradeDetailsStruct[],
      tradeInfo: MultiAssetInfoStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchTradeWithETH(
      tradeDetails: TradeDetailsStruct[],
      dustTokens: PromiseOrValue<string>[],
      feeDetails: FeeDetailsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    converter(overrides?: CallOverrides): Promise<BigNumber>;

    dao(overrides?: CallOverrides): Promise<BigNumber>;

    extraBool(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _marketRegistry: PromiseOrValue<string>,
      _cryptoPunk: PromiseOrValue<string>,
      _mooncat: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    marketplaceRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    multiAssetSwap(
      erc20Details: ERC20DetailsStruct,
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct[],
      erc1155Details: ERC1155DetailsStruct[],
      tradeDetails: TradeDetailsStruct[],
      tradeInfo: MultiAssetInfoStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    nftProfile(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "onERC721Received(address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    openForTrades(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    percentFeeToDao(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    rescueERC1155(
      asset: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rescueERC20(
      asset: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rescueERC721(
      asset: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rescueETH(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rescueMooncat(
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rescuePunk(
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBaseFee(
      _baseFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setConverter(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDao(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDaoFee(
      _percentFeeToDao: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setNftProfile(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOneTimeApproval(
      _approvals: ApprovalsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOpenForTrades(
      _openForTrades: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CRYPTO_PUNK(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MOONCAT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    batchTrade(
      erc20Details: ERC20DetailsStruct,
      tradeDetails: TradeDetailsStruct[],
      tradeInfo: MultiAssetInfoStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchTradeWithETH(
      tradeDetails: TradeDetailsStruct[],
      dustTokens: PromiseOrValue<string>[],
      feeDetails: FeeDetailsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    converter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dao(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    extraBool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _marketRegistry: PromiseOrValue<string>,
      _cryptoPunk: PromiseOrValue<string>,
      _mooncat: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    marketplaceRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multiAssetSwap(
      erc20Details: ERC20DetailsStruct,
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct[],
      erc1155Details: ERC1155DetailsStruct[],
      tradeDetails: TradeDetailsStruct[],
      tradeInfo: MultiAssetInfoStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    nftProfile(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    openForTrades(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    percentFeeToDao(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rescueERC1155(
      asset: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rescueERC20(
      asset: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rescueERC721(
      asset: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rescueETH(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rescueMooncat(
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rescuePunk(
      erc721Details: SpecialTransferHelper.ERC721DetailsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBaseFee(
      _baseFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setConverter(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDao(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDaoFee(
      _percentFeeToDao: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setNftProfile(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOneTimeApproval(
      _approvals: ApprovalsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOpenForTrades(
      _openForTrades: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      _new: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
