#!/bin/bash
# NFT Universe Clone - Local Demo Commands
# Run these commands in separate terminals

echo "========================================"
echo "   NFT MINTING APP - LOCAL DEMO SETUP"
echo "========================================"
echo ""
echo "📋 INSTRUCTIONS:"
echo "Open 3 separate terminals and run each command below in order"
echo ""
echo "========================================"
echo "TERMINAL 1: Start Blockchain"
echo "========================================"
echo ""
echo "cd ~/Work/nft-universe-clone && npx hardhat node"
echo ""
echo "⏳ Wait until you see:"
echo "   'Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/'"
echo ""
echo ""
echo "========================================"
echo "TERMINAL 2: Deploy Smart Contract"
echo "========================================"
echo ""
echo "cd ~/Work/nft-universe-clone && npx hardhat run scripts/deploy-local.js --network localhost"
echo ""
echo "⏳ Wait until you see:"
echo "   '✅ AIGeneratedNFT deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3'"
echo ""
echo ""
echo "========================================"
echo "TERMINAL 3: Start Web App"
echo "========================================"
echo ""
echo "cd ~/Work/nft-universe-clone && npm run dev"
echo ""
echo "⏳ Wait until you see:"
echo "   '✓ Ready in X.Xs'"
echo "   '- Local: http://localhost:8080'"
echo ""
echo ""
echo "========================================"
echo "THEN: Open Browser"
echo "========================================"
echo ""
echo "http://localhost:8080"
echo ""
echo "========================================"
