#!/bin/bash
# NFT Universe Clone - SETUP FOR NEW DEVELOPER
# Run these commands FIRST before running the 3-terminal demo

echo "========================================"
echo "   NFT MINTING APP - FIRST TIME SETUP"
echo "========================================"
echo ""
echo "Run these commands in order in ONE terminal"
echo ""

echo "========================================"
echo "STEP 1: Clone Repository"
echo "========================================"
echo ""
echo "git clone https://github.com/GeekyRiolu/MintForge.git nft-app"
echo "cd nft-app"
echo ""

echo "========================================"
echo "STEP 2: Install Dependencies"
echo "========================================"
echo ""
echo "npm install"
echo ""
echo "⏳ Wait for installation to complete (2-5 minutes)"
echo ""

echo "========================================"
echo "STEP 3: Check Node Version (Optional)"
echo "========================================"
echo ""
echo "node --version"
echo ""
echo "✅ Should be: v16 or higher (v18+ recommended)"
echo ""

echo "========================================"
echo "✅ SETUP COMPLETE!"
echo "========================================"
echo ""
echo "Now proceed with the 3-terminal demo:"
echo ""
echo "TERMINAL 1: npx hardhat node"
echo "TERMINAL 2: npx hardhat run scripts/deploy-local.js --network localhost"
echo "TERMINAL 3: npm run dev"
echo ""
echo "Then open: http://localhost:8080"
echo ""
