/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace OrderTypes {
  export type MakerOrderStruct = {
    isOrderAsk: PromiseOrValue<boolean>;
    signer: PromiseOrValue<string>;
    collection: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    tokenId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    strategy: PromiseOrValue<string>;
    currency: PromiseOrValue<string>;
    nonce: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    minPercentageToAsk: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type MakerOrderStructOutput = [
    boolean,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    number,
    string,
    string
  ] & {
    isOrderAsk: boolean;
    signer: string;
    collection: string;
    price: BigNumber;
    tokenId: BigNumber;
    amount: BigNumber;
    strategy: string;
    currency: string;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    minPercentageToAsk: BigNumber;
    params: string;
    v: number;
    r: string;
    s: string;
  };
}

export interface OrderValidatorV1Interface extends utils.Interface {
  functions: {
    "CRITERIA_GROUPS()": FunctionFragment;
    "INTERFACE_ID_ERC1155()": FunctionFragment;
    "INTERFACE_ID_ERC2981()": FunctionFragment;
    "INTERFACE_ID_ERC721()": FunctionFragment;
    "MAGIC_VALUE_EIP1271()": FunctionFragment;
    "TRANSFER_MANAGER_ERC1155()": FunctionFragment;
    "TRANSFER_MANAGER_ERC721()": FunctionFragment;
    "_DOMAIN_SEPARATOR()": FunctionFragment;
    "checkMultipleOrderValidities((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32)[])": FunctionFragment;
    "checkOrderValidity((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "checkValidityAmounts((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "checkValidityApprovalsAndBalances((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "checkValidityMinPercentageToAsk((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "checkValidityNonces((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "checkValiditySignature((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "checkValidityTimestamps((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "checkValidityWhitelists((bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "currencyManager()": FunctionFragment;
    "executionManager()": FunctionFragment;
    "looksRareExchange()": FunctionFragment;
    "royaltyFeeRegistry()": FunctionFragment;
    "transferSelectorNFT()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CRITERIA_GROUPS"
      | "INTERFACE_ID_ERC1155"
      | "INTERFACE_ID_ERC2981"
      | "INTERFACE_ID_ERC721"
      | "MAGIC_VALUE_EIP1271"
      | "TRANSFER_MANAGER_ERC1155"
      | "TRANSFER_MANAGER_ERC721"
      | "_DOMAIN_SEPARATOR"
      | "checkMultipleOrderValidities"
      | "checkOrderValidity"
      | "checkValidityAmounts"
      | "checkValidityApprovalsAndBalances"
      | "checkValidityMinPercentageToAsk"
      | "checkValidityNonces"
      | "checkValiditySignature"
      | "checkValidityTimestamps"
      | "checkValidityWhitelists"
      | "currencyManager"
      | "executionManager"
      | "looksRareExchange"
      | "royaltyFeeRegistry"
      | "transferSelectorNFT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CRITERIA_GROUPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INTERFACE_ID_ERC1155",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INTERFACE_ID_ERC2981",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INTERFACE_ID_ERC721",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAGIC_VALUE_EIP1271",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRANSFER_MANAGER_ERC1155",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRANSFER_MANAGER_ERC721",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkMultipleOrderValidities",
    values: [OrderTypes.MakerOrderStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "checkOrderValidity",
    values: [OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "checkValidityAmounts",
    values: [OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "checkValidityApprovalsAndBalances",
    values: [OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "checkValidityMinPercentageToAsk",
    values: [OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "checkValidityNonces",
    values: [OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "checkValiditySignature",
    values: [OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "checkValidityTimestamps",
    values: [OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "checkValidityWhitelists",
    values: [OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "currencyManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "looksRareExchange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyFeeRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferSelectorNFT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CRITERIA_GROUPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_ERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_ERC2981",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_ERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAGIC_VALUE_EIP1271",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRANSFER_MANAGER_ERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRANSFER_MANAGER_ERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMultipleOrderValidities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkOrderValidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkValidityAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkValidityApprovalsAndBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkValidityMinPercentageToAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkValidityNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkValiditySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkValidityTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkValidityWhitelists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "looksRareExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyFeeRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSelectorNFT",
    data: BytesLike
  ): Result;

  events: {};
}

export interface OrderValidatorV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OrderValidatorV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CRITERIA_GROUPS(overrides?: CallOverrides): Promise<[BigNumber]>;

    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<[string]>;

    INTERFACE_ID_ERC2981(overrides?: CallOverrides): Promise<[string]>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<[string]>;

    MAGIC_VALUE_EIP1271(overrides?: CallOverrides): Promise<[string]>;

    TRANSFER_MANAGER_ERC1155(overrides?: CallOverrides): Promise<[string]>;

    TRANSFER_MANAGER_ERC721(overrides?: CallOverrides): Promise<[string]>;

    _DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    checkMultipleOrderValidities(
      makerOrders: OrderTypes.MakerOrderStruct[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[][]] & { validationCodes: BigNumber[][] }>;

    checkOrderValidity(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { validationCodes: BigNumber[] }>;

    checkValidityAmounts(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { validationCode: BigNumber }>;

    checkValidityApprovalsAndBalances(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { validationCode: BigNumber }>;

    checkValidityMinPercentageToAsk(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { validationCode: BigNumber }>;

    checkValidityNonces(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { validationCode: BigNumber }>;

    checkValiditySignature(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { validationCode: BigNumber }>;

    checkValidityTimestamps(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { validationCode: BigNumber }>;

    checkValidityWhitelists(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { validationCode: BigNumber }>;

    currencyManager(overrides?: CallOverrides): Promise<[string]>;

    executionManager(overrides?: CallOverrides): Promise<[string]>;

    looksRareExchange(overrides?: CallOverrides): Promise<[string]>;

    royaltyFeeRegistry(overrides?: CallOverrides): Promise<[string]>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<[string]>;
  };

  CRITERIA_GROUPS(overrides?: CallOverrides): Promise<BigNumber>;

  INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<string>;

  INTERFACE_ID_ERC2981(overrides?: CallOverrides): Promise<string>;

  INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<string>;

  MAGIC_VALUE_EIP1271(overrides?: CallOverrides): Promise<string>;

  TRANSFER_MANAGER_ERC1155(overrides?: CallOverrides): Promise<string>;

  TRANSFER_MANAGER_ERC721(overrides?: CallOverrides): Promise<string>;

  _DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  checkMultipleOrderValidities(
    makerOrders: OrderTypes.MakerOrderStruct[],
    overrides?: CallOverrides
  ): Promise<BigNumber[][]>;

  checkOrderValidity(
    makerOrder: OrderTypes.MakerOrderStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  checkValidityAmounts(
    makerOrder: OrderTypes.MakerOrderStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkValidityApprovalsAndBalances(
    makerOrder: OrderTypes.MakerOrderStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkValidityMinPercentageToAsk(
    makerOrder: OrderTypes.MakerOrderStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkValidityNonces(
    makerOrder: OrderTypes.MakerOrderStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkValiditySignature(
    makerOrder: OrderTypes.MakerOrderStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkValidityTimestamps(
    makerOrder: OrderTypes.MakerOrderStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkValidityWhitelists(
    makerOrder: OrderTypes.MakerOrderStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  currencyManager(overrides?: CallOverrides): Promise<string>;

  executionManager(overrides?: CallOverrides): Promise<string>;

  looksRareExchange(overrides?: CallOverrides): Promise<string>;

  royaltyFeeRegistry(overrides?: CallOverrides): Promise<string>;

  transferSelectorNFT(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    CRITERIA_GROUPS(overrides?: CallOverrides): Promise<BigNumber>;

    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<string>;

    INTERFACE_ID_ERC2981(overrides?: CallOverrides): Promise<string>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<string>;

    MAGIC_VALUE_EIP1271(overrides?: CallOverrides): Promise<string>;

    TRANSFER_MANAGER_ERC1155(overrides?: CallOverrides): Promise<string>;

    TRANSFER_MANAGER_ERC721(overrides?: CallOverrides): Promise<string>;

    _DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    checkMultipleOrderValidities(
      makerOrders: OrderTypes.MakerOrderStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber[][]>;

    checkOrderValidity(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    checkValidityAmounts(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityApprovalsAndBalances(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityMinPercentageToAsk(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityNonces(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValiditySignature(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityTimestamps(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityWhitelists(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currencyManager(overrides?: CallOverrides): Promise<string>;

    executionManager(overrides?: CallOverrides): Promise<string>;

    looksRareExchange(overrides?: CallOverrides): Promise<string>;

    royaltyFeeRegistry(overrides?: CallOverrides): Promise<string>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    CRITERIA_GROUPS(overrides?: CallOverrides): Promise<BigNumber>;

    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<BigNumber>;

    INTERFACE_ID_ERC2981(overrides?: CallOverrides): Promise<BigNumber>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<BigNumber>;

    MAGIC_VALUE_EIP1271(overrides?: CallOverrides): Promise<BigNumber>;

    TRANSFER_MANAGER_ERC1155(overrides?: CallOverrides): Promise<BigNumber>;

    TRANSFER_MANAGER_ERC721(overrides?: CallOverrides): Promise<BigNumber>;

    _DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    checkMultipleOrderValidities(
      makerOrders: OrderTypes.MakerOrderStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkOrderValidity(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityAmounts(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityApprovalsAndBalances(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityMinPercentageToAsk(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityNonces(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValiditySignature(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityTimestamps(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkValidityWhitelists(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currencyManager(overrides?: CallOverrides): Promise<BigNumber>;

    executionManager(overrides?: CallOverrides): Promise<BigNumber>;

    looksRareExchange(overrides?: CallOverrides): Promise<BigNumber>;

    royaltyFeeRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    CRITERIA_GROUPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    INTERFACE_ID_ERC1155(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INTERFACE_ID_ERC2981(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INTERFACE_ID_ERC721(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAGIC_VALUE_EIP1271(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TRANSFER_MANAGER_ERC1155(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TRANSFER_MANAGER_ERC721(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkMultipleOrderValidities(
      makerOrders: OrderTypes.MakerOrderStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkOrderValidity(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkValidityAmounts(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkValidityApprovalsAndBalances(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkValidityMinPercentageToAsk(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkValidityNonces(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkValiditySignature(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkValidityTimestamps(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkValidityWhitelists(
      makerOrder: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currencyManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executionManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    looksRareExchange(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    royaltyFeeRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferSelectorNFT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
