/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface TradingRewardsDistributorInterface extends utils.Interface {
  functions: {
    "BUFFER_ADMIN_WITHDRAW()": FunctionFragment;
    "amountClaimedByUser(address)": FunctionFragment;
    "canClaim(address,uint256,bytes32[])": FunctionFragment;
    "claim(uint256,bytes32[])": FunctionFragment;
    "currentRewardRound()": FunctionFragment;
    "hasUserClaimedForRewardRound(uint256,address)": FunctionFragment;
    "lastPausedTimestamp()": FunctionFragment;
    "looksRareToken()": FunctionFragment;
    "maximumAmountPerUserInCurrentTree()": FunctionFragment;
    "merkleRootOfRewardRound(uint256)": FunctionFragment;
    "merkleRootUsed(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "pauseDistribution()": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpauseDistribution()": FunctionFragment;
    "updateTradingRewards(bytes32,uint256)": FunctionFragment;
    "withdrawTokenRewards(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BUFFER_ADMIN_WITHDRAW"
      | "amountClaimedByUser"
      | "canClaim"
      | "claim"
      | "currentRewardRound"
      | "hasUserClaimedForRewardRound"
      | "lastPausedTimestamp"
      | "looksRareToken"
      | "maximumAmountPerUserInCurrentTree"
      | "merkleRootOfRewardRound"
      | "merkleRootUsed"
      | "owner"
      | "pauseDistribution"
      | "paused"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpauseDistribution"
      | "updateTradingRewards"
      | "withdrawTokenRewards"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BUFFER_ADMIN_WITHDRAW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amountClaimedByUser",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "canClaim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRewardRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserClaimedForRewardRound",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPausedTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "looksRareToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maximumAmountPerUserInCurrentTree",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRootOfRewardRound",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRootUsed",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseDistribution",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseDistribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateTradingRewards",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokenRewards",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "BUFFER_ADMIN_WITHDRAW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountClaimedByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentRewardRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserClaimedForRewardRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPausedTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "looksRareToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maximumAmountPerUserInCurrentTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleRootOfRewardRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleRootUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTradingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokenRewards",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "RewardsClaim(address,uint256,uint256)": EventFragment;
    "TokenWithdrawnOwner(uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "UpdateTradingRewards(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardsClaim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWithdrawnOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateTradingRewards"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RewardsClaimEventObject {
  user: string;
  rewardRound: BigNumber;
  amount: BigNumber;
}
export type RewardsClaimEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  RewardsClaimEventObject
>;

export type RewardsClaimEventFilter = TypedEventFilter<RewardsClaimEvent>;

export interface TokenWithdrawnOwnerEventObject {
  amount: BigNumber;
}
export type TokenWithdrawnOwnerEvent = TypedEvent<
  [BigNumber],
  TokenWithdrawnOwnerEventObject
>;

export type TokenWithdrawnOwnerEventFilter =
  TypedEventFilter<TokenWithdrawnOwnerEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UpdateTradingRewardsEventObject {
  rewardRound: BigNumber;
}
export type UpdateTradingRewardsEvent = TypedEvent<
  [BigNumber],
  UpdateTradingRewardsEventObject
>;

export type UpdateTradingRewardsEventFilter =
  TypedEventFilter<UpdateTradingRewardsEvent>;

export interface TradingRewardsDistributor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TradingRewardsDistributorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BUFFER_ADMIN_WITHDRAW(overrides?: CallOverrides): Promise<[BigNumber]>;

    amountClaimedByUser(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    canClaim(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber]>;

    claim(
      amount: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentRewardRound(overrides?: CallOverrides): Promise<[BigNumber]>;

    hasUserClaimedForRewardRound(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lastPausedTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    looksRareToken(overrides?: CallOverrides): Promise<[string]>;

    maximumAmountPerUserInCurrentTree(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    merkleRootOfRewardRound(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    merkleRootUsed(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pauseDistribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpauseDistribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateTradingRewards(
      merkleRoot: PromiseOrValue<BytesLike>,
      newMaximumAmountPerUser: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawTokenRewards(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  BUFFER_ADMIN_WITHDRAW(overrides?: CallOverrides): Promise<BigNumber>;

  amountClaimedByUser(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  canClaim(
    user: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    merkleProof: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber]>;

  claim(
    amount: PromiseOrValue<BigNumberish>,
    merkleProof: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentRewardRound(overrides?: CallOverrides): Promise<BigNumber>;

  hasUserClaimedForRewardRound(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lastPausedTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  looksRareToken(overrides?: CallOverrides): Promise<string>;

  maximumAmountPerUserInCurrentTree(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  merkleRootOfRewardRound(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  merkleRootUsed(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pauseDistribution(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpauseDistribution(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateTradingRewards(
    merkleRoot: PromiseOrValue<BytesLike>,
    newMaximumAmountPerUser: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawTokenRewards(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BUFFER_ADMIN_WITHDRAW(overrides?: CallOverrides): Promise<BigNumber>;

    amountClaimedByUser(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canClaim(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber]>;

    claim(
      amount: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    currentRewardRound(overrides?: CallOverrides): Promise<BigNumber>;

    hasUserClaimedForRewardRound(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lastPausedTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    looksRareToken(overrides?: CallOverrides): Promise<string>;

    maximumAmountPerUserInCurrentTree(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merkleRootOfRewardRound(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    merkleRootUsed(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pauseDistribution(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpauseDistribution(overrides?: CallOverrides): Promise<void>;

    updateTradingRewards(
      merkleRoot: PromiseOrValue<BytesLike>,
      newMaximumAmountPerUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawTokenRewards(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RewardsClaim(address,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      rewardRound?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): RewardsClaimEventFilter;
    RewardsClaim(
      user?: PromiseOrValue<string> | null,
      rewardRound?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): RewardsClaimEventFilter;

    "TokenWithdrawnOwner(uint256)"(
      amount?: null
    ): TokenWithdrawnOwnerEventFilter;
    TokenWithdrawnOwner(amount?: null): TokenWithdrawnOwnerEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "UpdateTradingRewards(uint256)"(
      rewardRound?: PromiseOrValue<BigNumberish> | null
    ): UpdateTradingRewardsEventFilter;
    UpdateTradingRewards(
      rewardRound?: PromiseOrValue<BigNumberish> | null
    ): UpdateTradingRewardsEventFilter;
  };

  estimateGas: {
    BUFFER_ADMIN_WITHDRAW(overrides?: CallOverrides): Promise<BigNumber>;

    amountClaimedByUser(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canClaim(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      amount: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentRewardRound(overrides?: CallOverrides): Promise<BigNumber>;

    hasUserClaimedForRewardRound(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastPausedTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    looksRareToken(overrides?: CallOverrides): Promise<BigNumber>;

    maximumAmountPerUserInCurrentTree(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merkleRootOfRewardRound(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merkleRootUsed(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pauseDistribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpauseDistribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateTradingRewards(
      merkleRoot: PromiseOrValue<BytesLike>,
      newMaximumAmountPerUser: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawTokenRewards(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BUFFER_ADMIN_WITHDRAW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    amountClaimedByUser(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canClaim(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      amount: PromiseOrValue<BigNumberish>,
      merkleProof: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentRewardRound(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasUserClaimedForRewardRound(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastPausedTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    looksRareToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maximumAmountPerUserInCurrentTree(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    merkleRootOfRewardRound(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    merkleRootUsed(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pauseDistribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpauseDistribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateTradingRewards(
      merkleRoot: PromiseOrValue<BytesLike>,
      newMaximumAmountPerUser: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawTokenRewards(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
