import { useCallback, useState } from 'react';
import { useAccount, useContract, useSigner } from 'wagmi';
import { Contract } from 'ethers';

interface MintParams {
  imageUri: string;
  prompt: string;
  name?: string;
  description?: string;
}

interface MintState {
  isLoading: boolean;
  isSuccess: boolean;
  error: string | null;
  txHash: string | null;
  tokenId: string | null;
}

const INITIAL_STATE: MintState = {
  isLoading: false,
  isSuccess: false,
  error: null,
  txHash: null,
  tokenId: null,
};

/**
 * Hook for minting AI-generated NFTs
 * Requires contract address in environment variables
 */
export function useNFTMint(contractAddress?: string, contractABI?: any) {
  const { address } = useAccount();
  const { data: signer } = useSigner();
  const [state, setState] = useState<MintState>(INITIAL_STATE);

  const mint = useCallback(
    async (params: MintParams) => {
      if (!address) {
        setState(prev => ({
          ...prev,
          error: 'Wallet not connected',
        }));
        return;
      }

      if (!signer) {
        setState(prev => ({
          ...prev,
          error: 'Signer not available',
        }));
        return;
      }

      if (!contractAddress || !contractABI) {
        setState(prev => ({
          ...prev,
          error: 'Contract address or ABI not configured',
        }));
        return;
      }

      setState(prev => ({
        ...prev,
        isLoading: true,
        error: null,
      }));

      try {
        // Create contract instance
        const contract = new Contract(contractAddress, contractABI, signer);

        // Prepare metadata
        const metadata = {
          name: params.name || `AI NFT - ${new Date().toLocaleString()}`,
          description: params.description || params.prompt,
          image: params.imageUri,
          prompt: params.prompt,
          attributes: [
            {
              trait_type: 'Generated By',
              value: 'Mintly AI',
            },
            {
              trait_type: 'Prompt',
              value: params.prompt,
            },
          ],
        };

        // Upload metadata to IPFS
        const metadataUri = await uploadToIPFS(metadata);

        // Call mint function - adjust based on your contract
        // This is a generic example - modify according to your contract's mint function
        const tx = await contract.mint(address, metadataUri);
        const receipt = await tx.wait();

        // Extract token ID from event (adjust based on your contract events)
        let tokenId: string | null = null;
        if (receipt?.events) {
          const transferEvent = receipt.events.find(
            (e: any) => e.event === 'Transfer',
          );
          if (transferEvent) {
            tokenId = transferEvent.args?.tokenId?.toString();
          }
        }

        setState(prev => ({
          ...prev,
          isLoading: false,
          isSuccess: true,
          txHash: tx.hash,
          tokenId: tokenId || 'unknown',
        }));

        return {
          success: true,
          txHash: tx.hash,
          tokenId,
        };
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Mint failed';
        console.error('Mint error:', error);

        setState(prev => ({
          ...prev,
          isLoading: false,
          error: errorMessage,
        }));

        return {
          success: false,
          error: errorMessage,
        };
      }
    },
    [address, signer, contractAddress, contractABI],
  );

  const reset = useCallback(() => {
    setState(INITIAL_STATE);
  }, []);

  return { ...state, mint, reset };
}

/**
 * Upload metadata to IPFS via Pinata or NFT.storage
 */
async function uploadToIPFS(metadata: any): Promise<string> {
  const provider = process.env.NEXT_PUBLIC_IPFS_PROVIDER || 'nft-storage';

  if (provider === 'pinata') {
    return uploadToPinata(metadata);
  }

  return uploadToNFTStorage(metadata);
}

/**
 * Upload to NFT.storage (free, no API key required for basic usage)
 */
async function uploadToNFTStorage(metadata: any): Promise<string> {
  const apiKey = process.env.NEXT_PUBLIC_NFT_STORAGE_KEY;

  if (!apiKey) {
    throw new Error('NFT_STORAGE_KEY not configured');
  }

  const response = await fetch('https://api.nft.storage/upload', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(metadata),
  });

  if (!response.ok) {
    throw new Error('Failed to upload to NFT.storage');
  }

  const data = (await response.json()) as { ok: boolean; value: { cid: string } };
  return `ipfs://${data.value.cid}`;
}

/**
 * Upload to Pinata
 */
async function uploadToPinata(metadata: any): Promise<string> {
  const apiKey = process.env.NEXT_PUBLIC_PINATA_API_KEY;
  const apiSecret = process.env.PINATA_API_SECRET;

  if (!apiKey || !apiSecret) {
    throw new Error('Pinata credentials not configured');
  }

  const response = await fetch('https://api.pinata.cloud/pinning/pinJSONToIPFS', {
    method: 'POST',
    headers: {
      pinata_api_key: apiKey,
      pinata_secret_api_key: apiSecret,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(metadata),
  });

  if (!response.ok) {
    throw new Error('Failed to upload to Pinata');
  }

  const data = (await response.json()) as { IpfsHash: string };
  return `ipfs://${data.IpfsHash}`;
}
