import { useCallback, useState } from 'react';
import { useAccount, useSigner } from 'wagmi';
import { Contract, ContractInterface } from 'ethers';

interface MintParams {
  imageUri: string;
  prompt: string;
  name?: string;
  description?: string;
}

interface MintState {
  isLoading: boolean;
  isSuccess: boolean;
  error: string | null;
  txHash: string | null;
  tokenId: string | null;
}

type NFTMetadata = {
  name: string;
  description: string;
  image: string;
  prompt: string;
  attributes: {
    trait_type: string;
    value: string;
  }[];
};

const INITIAL_STATE: MintState = {
  isLoading: false,
  isSuccess: false,
  error: null,
  txHash: null,
  tokenId: null,
};

/**
 * Hook for minting AI-generated NFTs
 * Requires contract address in environment variables
 */
export function useNFTMint(
  contractAddress?: string,
  contractABI?: ContractInterface,
) {
  const { address } = useAccount();
  const { data: signer } = useSigner();
  const [state, setState] = useState<MintState>(INITIAL_STATE);

  const mint = useCallback(
    async (params: MintParams) => {
      if (!address) {
        setState(prev => ({
          ...prev,
          error: 'Wallet not connected',
        }));
        return;
      }

      if (!signer) {
        setState(prev => ({
          ...prev,
          error: 'Signer not available',
        }));
        return;
      }

      if (!contractAddress || !contractABI) {
        setState(prev => ({
          ...prev,
          error: 'Contract address or ABI not configured',
        }));
        return;
      }

      setState(prev => ({
        ...prev,
        isLoading: true,
        error: null,
      }));

      try {
        // Create contract instance
        const contract = new Contract(contractAddress, contractABI, signer);

        // Prepare metadata
        const metadata = {
          name: params.name || `AI NFT - ${new Date().toLocaleString()}`,
          description: params.description || params.prompt,
          image: params.imageUri,
          prompt: params.prompt,
          attributes: [
            {
              trait_type: 'Generated By',
              value: 'Mintly AI',
            },
            {
              trait_type: 'Prompt',
              value: params.prompt,
            },
          ],
        };

        // Upload metadata to IPFS
        const metadataUri = await uploadToIPFS(metadata);

        // Call mint function - adjust based on your contract
        // This is a generic example - modify according to your contract's mint function
        const tx = await contract.mint(address, metadataUri);
        const receipt = await tx.wait();

        // Extract token ID from event (adjust based on your contract events)
        let tokenId: string | null = null;
        if (receipt?.events) {
          const transferEvent = receipt.events.find(e => e.event === 'Transfer');
          if (transferEvent) {
            tokenId = transferEvent.args?.tokenId?.toString();
          }
        }

        setState(prev => ({
          ...prev,
          isLoading: false,
          isSuccess: true,
          txHash: tx.hash,
          tokenId: tokenId || 'unknown',
        }));

        return {
          success: true,
          txHash: tx.hash,
          tokenId,
        };
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Mint failed';
        console.error('Mint error:', error);

        setState(prev => ({
          ...prev,
          isLoading: false,
          error: errorMessage,
        }));

        return {
          success: false,
          error: errorMessage,
        };
      }
    },
    [address, signer, contractAddress, contractABI],
  );

  const reset = useCallback(() => {
    setState(INITIAL_STATE);
  }, []);

  return { ...state, mint, reset };
}

/**
 * Upload metadata to IPFS via the server-side IPFS API route
 */
async function uploadToIPFS(metadata: NFTMetadata): Promise<string> {
  const response = await fetch('/api/ipfs', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      type: 'metadata',
      metadata,
    }),
  });

  const result = (await response.json()) as {
    success: boolean;
    ipfsUrl?: string;
    error?: string;
  };

  if (!response.ok || !result.success || !result.ipfsUrl) {
    throw new Error(result.error || 'Failed to upload metadata to IPFS');
  }

  return result.ipfsUrl;
}
