function getDemoConfig(env) {
  return {
    appUrl: env.APP_URL || 'http://127.0.0.1:8080',
    rpcUrl: env.LOCAL_RPC_URL || 'http://127.0.0.1:8545',
    privateKey:
      env.LOCAL_DEMO_PRIVATE_KEY ||
      '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
    contractAddress:
      env.CONTRACT_ADDRESS || env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS || '',
  };
}

function buildMetadata({ prompt, imageUri }) {
  return {
    name: `AI NFT - ${prompt}`,
    description: `Generated by Mintly AI\n\nPrompt: ${prompt}`,
    image: imageUri,
    prompt,
    attributes: [
      {
        trait_type: 'Generated By',
        value: 'Mintly AI',
      },
      {
        trait_type: 'Prompt',
        value: prompt,
      },
    ],
  };
}

module.exports = {
  buildMetadata,
  getDemoConfig,
};
